Repository chipsec/chipsec, pull requests merged in 2021-09, with the labels that each got.

#1256 Show only main docstring for modules
  docs/sphinx/removeStrRst.py
Labels: next release

#1268 Minor fixes to documentation
  docs/sphinx/Install in Windows.rst
  docs/sphinx/Vulnerabilities-and-CHIPSEC-Modules.rst
Labels: next release

#1272 Remove ubuntu16.04 per support being removed.
  .github/workflows/tests.yml
Labels: bug, next release

#1273 Dev 2.0.0 config fixes
  chipsec/cfg/8086/HOSTCTL/hostctl2.xml
  chipsec/config.py
Labels: dev branch

#1257 Expand usage documentation in rogue_mmio_bar.py
  chipsec/modules/tools/smm/rogue_mmio_bar.py
Labels: enhancement, next release

#1264 Add docstrings to some HALs
  chipsec/hal/paging.py
  chipsec/hal/smbios.py
  chipsec/hal/uefi_fv.py
Labels: next release

#1265 Fix exception when loaded config does not have a sku element
  chipsec/chipset.py
Labels: bug, next release

#1266 Updates to spd_wd.py
  chipsec/modules/common/spd_wd.py
Labels: bug, next release

#1271 Move docstring from class
  chipsec/utilcmd/acpi_cmd.py
  chipsec/utilcmd/cmos_cmd.py
  chipsec/utilcmd/config_cmd.py
  chipsec/utilcmd/cpu_cmd.py
  chipsec/utilcmd/decode_cmd.py
  chipsec/utilcmd/deltas_cmd.py
  chipsec/utilcmd/desc_cmd.py
  chipsec/utilcmd/ec_cmd.py
  chipsec/utilcmd/igd_cmd.py
  chipsec/utilcmd/interrupts_cmd.py
  chipsec/utilcmd/io_cmd.py
  chipsec/utilcmd/iommu_cmd.py
  chipsec/utilcmd/mem_cmd.py
  chipsec/utilcmd/mmcfg_base_cmd.py
  chipsec/utilcmd/mmcfg_cmd.py
  chipsec/utilcmd/mmio_cmd.py
  chipsec/utilcmd/msgbus_cmd.py
  chipsec/utilcmd/msr_cmd.py
  chipsec/utilcmd/pci_cmd.py
  chipsec/utilcmd/reg_cmd.py
  chipsec/utilcmd/smbios_cmd.py
  chipsec/utilcmd/smbus_cmd.py
  chipsec/utilcmd/spd_cmd.py
  chipsec/utilcmd/spi_cmd.py
  chipsec/utilcmd/spidesc_cmd.py
  chipsec/utilcmd/tpm_cmd.py
  chipsec/utilcmd/ucode_cmd.py
  chipsec/utilcmd/uefi_cmd.py
  chipsec/utilcmd/vmem_cmd.py
  chipsec/utilcmd/vmm_cmd.py
Labels: next release

#1270 Fix MMIO multi-bus support in mmio.py and chipset.py
  chipsec/chipset.py
  chipsec/hal/mmio.py
Labels: bug, next release, validation required
