Repository chipsec/chipsec, pull requests merged in 2021-06, with the labels that each got.

#1184 Fixup linux swsmi assembly
  drivers/linux/amd64/cpu.asm
Labels: Next Release, bug

#1198 Add register type checks
  chipsec/chipset.py
Labels: Next Release, enhancement

#1197 Update AUTHORS file
  AUTHORS
Labels: Next Release

#1206 Create manual script enhancements
  docs/create_manual.cmd
  docs/create_manual.sh
Labels: Next Release, enhancement

#1211 Add write_register() return
  chipsec/chipset.py
Labels: Next Release, enhancement

#1215 Fix issue with mmio r/w in windows
  chipsec/helper/win/win32helper.py
  drivers/win7/driver.c
  drivers/win7/include/chipsec.h
Labels: Next Release, bug

#1212 Change SPIBAR mask (Issue #927)
  chipsec/cfg/8086/dnv.xml
Labels: Next Release

#1214 Update 01.org mailing list link
  README.md
Labels: Next Release

#1202 Add windows_requirements.txt
  windows_requirements.txt
Labels: Next Release, enhancement

#1217 Fix TPM locality memory mapping bug caused by argparse changes
  chipsec/utilcmd/tpm_cmd.py
Labels: Next Release, bug

#1207 Symbol lookup and various other fixes
  drivers/linux/chipsec_km.c
Labels: Next Release, bug, enhancement

#1192 Update pch5xxh
  chipsec/cfg/8086/pch_5xxh.xml
  chipsec/cfg/8086/pch_5xxlp.xml
Labels: Next Release, enhancement

#1219 Add setuptools to windows_requirements.txt
  windows_requirements.txt
Labels: Next Release, enhancement

#1209 Minor improvements to sinkhole.py
  chipsec/modules/tools/cpu/sinkhole.py
Labels: Next Release, enhancement

#1216 Update Windows Installation and other improvements
  docs/sphinx/Contact.rst
  docs/sphinx/Download.rst
  docs/sphinx/Install in Windows.rst
  docs/sphinx/_images/GHRepo.png
  docs/sphinx/_images/LR.png
  docs/sphinx/_images/chipsec_favicon.jpg
  docs/sphinx/conf.py
  docs/sphinx/index.rst
Labels: Next Release, enhancement

#1221 Update ABASE and PWRMBASE
  chipsec/cfg/8086/pch_5xxh.xml
  chipsec/cfg/8086/pch_5xxlp.xml
Labels: Next Release, enhancement
