Repository chipsec/chipsec, pull requests merged in 2021-01, with the labels that each got.

#1067 Move bios_smi.py control
  chipsec/modules/common/bios_smi.py
Labels: Next Release, enhancement

#1068 Update authors file
  AUTHORS
Labels: Next Release

#1070 Added log message to print actual DIDs if using -p or --pch
  chipsec/chipset.py
Labels: Next Release, enhancement

#1071 Fixed build error on latest Ubuntu
  drivers/linux/Makefile
Labels: Next Release, bug

#1072 Update mmcfg_cmd.py CLI
  chipsec/utilcmd/mmcfg_base_cmd.py
  chipsec/utilcmd/mmcfg_cmd.py
Labels: Next Release, enhancement

#1073 Update vmm_cmd.py CLI
  chipsec/utilcmd/vmm_cmd.py
Labels: Next Release, enhancement

#1074 Update msgbus_cmd.py CLI
  chipsec/utilcmd/msgbus_cmd.py
Labels: Next Release, enhancement

#1076 Update reg_cmd.py CLI
  chipsec/utilcmd/reg_cmd.py
Labels: Next Release, enhancement

#1077 Changes in modules for manual
  chipsec/cfg/8086/sfdp.xml
  chipsec/hal/msgbus.py
  chipsec/hal/spd.py
  chipsec/modules/common/cpu/cpu_info.py
  chipsec/modules/common/cpu/ia_untrusted.py
  chipsec/modules/common/me_mfg_mode.py
  chipsec/modules/tools/vmm/hv/hypercall.py
  chipsec/modules/tools/vmm/hv/hypercallfuzz.py
  chipsec/modules/tools/vmm/hv/synth_dev.py
  chipsec/modules/tools/vmm/hv/synth_kbd.py
  chipsec/modules/tools/vmm/hv/vmbus.py
  chipsec/modules/tools/vmm/hv/vmbusfuzz.py
  chipsec/modules/tools/vmm/xen/hypercall.py
  chipsec/modules/tools/vmm/xen/hypercallfuzz.py
  chipsec/utilcmd/mem_cmd.py
Labels: Next Release, enhancement

#1079 Update spd_cmd.py CLI
  chipsec/utilcmd/spd_cmd.py
Labels: Next Release, enhancement

#1080 Update spidesc_cmd.py CLI
  chipsec/utilcmd/spidesc_cmd.py
Labels: Next Release, enhancement

#1081 Fix spd.py decode fn
  chipsec/hal/spd.py
Labels: Next Release, bug

#1082 Add very verbose command-line option
  chipsec_main.py
  chipsec_util.py
Labels: Next Release, enhancement

#1085 Minor typo in hal\interrupts.py
  chipsec/hal/interrupts.py
Labels: Next Release, bug

#1075 Updating manual to 1.5.8
  chipsec-manual.pdf
Labels: Next Release, enhancement

#1066 Expand the conditional compilation based on d02624b to support more P…
  drivers/linux/chipsec_km.c
Labels: Next Release, bug

#1087 Fixed error in uefi shell for spectre v2 test
  chipsec/modules/common/cpu/spectre_v2.py
Labels: Next Release, bug

#1089 Updating to 1.5.9
  chipsec/VERSION
Labels: Next Release
