Repository chipsec/chipsec, pull requests merged in 2021-04, with the labels that each got.

#1137 Change macro used for writing to MMIO in Win driver
  chipsec/helper/win/win32helper.py
  drivers/win7/driver.c
  drivers/win7/include/chipsec.h
Labels: Next Release, bug

#1151 Fix missing type attribute
  chipsec/cfg/8086/pch_5xxh.xml
Labels: Next Release, bug

#1148 Update exception logic from cs exception changes
  chipsec/chipset.py
Labels: Next Release, bug

#1102 Logger: prefer WConio2 over the original WConio.
  chipsec/logger.py
Labels: Next Release

#1171 sgx_check: Update missed formatting changes
  chipsec/modules/common/sgx_check.py
Labels: Next Release

#1166 Generate 12-byte fake TPM event in EFIFirmwareBlob test
  tests/software/test_tpm_eventlog.py
Labels: Next Release

#1165 Switch to MEI1 device definition
  chipsec/cfg/8086/common.xml
Labels: Next Release, enhancement

#1162 Fix payload reading for smi_smmc.
  chipsec/utilcmd/interrupts_cmd.py
Labels: Next Release, bug

#1161 Added partial MMIO region dump
  chipsec/utilcmd/mmio_cmd.py
Labels: Next Release, enhancement

#1157 Add bytes support to uefivar_fuzz.py
  chipsec/modules/tools/uefi/uefivar_fuzz.py
Labels: Next Release, enhancement

#1152 Updated functions to display register in verbose mode.
  chipsec/chipset.py
Labels: Next Release, enhancement

#1149 Fix hal.spi bytearray verbose print
  chipsec/hal/spi.py
Labels: Next Release, bug
