Repository chipsec/chipsec, pull requests merged in 2021-12, with the labels that each got.

#1311 Add mmio and io BAR descriptions for Renoir
  chipsec/cfg/1022/renoir.xml
  chipsec/cfg/chipsec_cfg.xsd
Labels: bug, next release

#1292 Log QWORD memory read as "qword"
  chipsec/hal/physmem.py
Labels: next release

#1297 Add usage documentation to smrr.py
  chipsec/modules/common/smrr.py
Labels: enhancement, next release

#1298 Add usage documentation to smm_dma.py
  chipsec/modules/common/smm_dma.py
Labels: enhancement, next release

#1301 Add functionality to search for metadata tags in test modules
  chipsec/module.py
  chipsec_main.py
Labels: enhancement, next release

#1293 Use copy_from_kernel_nofault when reading physical memory
  drivers/linux/chipsec_km.c
Labels: enhancement, next release

#1302 Added ability to dump unnamed MMIO regions
  chipsec/utilcmd/mmio_cmd.py
Labels: enhancement, next release

#1304 Handle case when rsdp_pa is not found within _find_RSDP_in_EFI_config_table
  chipsec/hal/acpi.py
Labels: enhancement, next release

#1305 Modify is_supported and logic to support other OS
  chipsec/modules/common/wsmt.py
Labels: enhancement, next release

#1323 Better remap.py logic if not reading REMAP registers properly
  chipsec/modules/common/remap.py
Labels: enhancement, next release

#1324 Fix scan_image.py arg count check
  chipsec/modules/tools/uefi/scan_image.py
Labels: bug, next release

#1325 Detect presence of SKU entries
  chipsec/chipset.py
Labels: bug, next release

#1329 Update contact information
  AUTHORS
  README
  README.md
  docs/sphinx/start/Contact.rst
Labels: next release
