Repository chipsec/chipsec, pull requests merged in 2021-05, with the labels that each got.

#1178 Change xenial to newer distros
  .travis.yml
Labels: Next Release

#1103 Add message when there are multiple PCHs with same DID
  chipsec/chipset.py
Labels: Next Release, enhancement

#1131 Updating BaseModule methods
  chipsec/module_common.py
Labels: Next Release, enhancement

#1156 Remove underscores that are no longer needed
  chipsec/utilcmd/pci_cmd.py
Labels: Next Release

#1158 linuxhelper.py minor improvements
  chipsec/helper/linux/linuxhelper.py
Labels: Next Release, enhancement

#1144 Fix smm_ptr.py sig bytearray
  chipsec/modules/tools/smm/smm_ptr.py
Labels: Next Release, enhancement

#1108 Fix the access_uefispec module
  chipsec/modules/common/uefi/access_uefispec.py
Labels: Next Release, enhancement

#1177 Changes to enable CONSISTENCY_CHECKING
  chipsec/chipset.py
  chipsec/hal/iobar.py
  chipsec/hal/mmio.py
Labels: Next Release

#1179 Update spi_uefi.py to handle the corrupted GUID
  chipsec/hal/spi_uefi.py
Labels: Next Release

#1174 PCH 4xx series updates
  chipsec/cfg/8086/pch_4xx.xml
  chipsec/cfg/8086/pch_4xxh.xml
  chipsec/cfg/8086/pch_4xxlp.xml
Labels: Next Release

#1169 Configure GitHub Actions to test some features
  .github/workflows/tests.yml
  tests/hardware/test_generic.py
Labels: Next Release, enhancement

#1172 Simplify parsing /proc/kallsyms in Linux kernel module
  drivers/linux/chipsec_km.c
Labels: Next Release, enhancement

#1182 Fix issue when trying to access SB on some platforms
  chipsec/hal/msgbus.py
Labels: Next Release, bug

#1183 Fixed MMCFG accesses not DWORD aligned
  chipsec/hal/mmio.py
Labels: Next Release

#1186 Fix logger when logfile and ALWAYS_FLUSH
  chipsec/logger.py
Labels: Next Release, bug

#1187 win32helper.py variable attrs update
  chipsec/helper/win/win32helper.py
Labels: Next Release

#1189 Add fixed addr to SBREGBAR
  chipsec/cfg/8086/pch_c620.xml
Labels: Next Release, enhancement

#1190 Fix unassigned variable
  chipsec/hal/mmio.py
Labels: Next Release, bug

#1191 Add WOPCM field
  chipsec/cfg/8086/tglu.xml
Labels: Next Release

#1194 scan_blocked.py exit if no FW image found
  chipsec/modules/tools/uefi/scan_blocked.py
Labels: Next Release, enhancement

#1196 Add CML SKU DIDs
  chipsec/cfg/8086/cml.xml
Labels: Next Release, enhancement

#1188 Update rouge_mmio_bar to work with python3
  chipsec/modules/tools/smm/rogue_mmio_bar.py
Labels: Next Release, bug

#1125 Simplify the Makefile used by Linux kernel module
  drivers/linux/Makefile
Labels: Next Release
