Repository chipsec/chipsec, pull requests merged in 2021-02, with the labels that each got.

#1093 Changing helper calls to HAL calls
  chipsec/modules/common/debugenabled.py
  chipsec/modules/tools/vmm/xen/hypercall.py
Labels: Next Release

#1036 Using CONFIG_EFI instead of user defined HAS_EFI
  drivers/linux/chipsec_km.c
Labels: Next Release

#1090 Minor typos in smm_ptr.py
  chipsec/modules/tools/smm/smm_ptr.py
Labels: Next Release

#1095 Fix #1086: Linux kernel v5.10 removed the old good syscalls get_fs/se…
  drivers/linux/chipsec_km.c
Labels: Next Release

#1096 Fix two memory leak bugs
  drivers/linux/chipsec_km.c
Labels: Next Release

#1099 Fix Makefile to work with DKMS
  drivers/linux/Makefile
Labels: Next Release, bug

#1091 Add lock and lockedby to configuration
  chipsec/cfg/template.xml
  chipsec/chipset.py
Labels: enhancement

#1105 spi_fdopss check for FDOPSS
  chipsec/modules/common/spi_fdopss.py
Labels: Next Release, enhancement
