Repository chipsec/chipsec, pull requests merged in 2021-03, with the labels that each got.

#1111 Update README.md
  README.md
Labels: Next Release, enhancement

#1107 Fixed parameter processing in I/O command
  chipsec/utilcmd/io_cmd.py
Labels: Next Release

#1084 Update interrupts_cmd.py CLI
  chipsec/utilcmd/interrupts_cmd.py
Labels: Next Release, enhancement, help wanted, next minor version

#1109 Fix copy error when building driver with a space in the path
  drivers/win7/chipsec_hlpr.vcxproj
Labels: Next Release, bug

#1128 Support overriding Linux source path
  drivers/linux/Makefile
Labels: Next Release, bug

#1126 Fix to mmio access in native mode
  chipsec/helper/linux/linuxhelper.py
Labels: Next Release, bug

#1136 Update travis.yml for macos
  .travis.yml
Labels: Next Release

#1083 Update pci_cmd.py CLI
  chipsec/utilcmd/pci_cmd.py
Labels: Next Release, enhancement, help wanted, next minor version

#1114 smm_code_chk.py capture self.res
  chipsec/modules/common/smm_code_chk.py
Labels: Next Release

#1117 Add MosaicRegressor UEFI RK to blockedlist
  chipsec/modules/tools/uefi/blockedlist.json
Labels: Next Release, enhancement

#1118 Add port options to send_smmc_SMI()
  chipsec/hal/interrupts.py
Labels: Next Release, enhancement, next minor version

#1121 [Linux driver] Fix dkms.conf
  drivers/linux/dkms.conf
Labels: Next Release

#1127 Fix error message when the Linux kernel module fails to load
  chipsec/helper/linux/linuxhelper.py
Labels: Next Release, bug

#1132 Update log_parser requirements.txt
  chipsec_tools/log_parser/requirements.txt
Labels: Next Release, bug, question

#1106 Add TGLU configuration
  chipsec/cfg/8086/tglu.xml
Labels: Next Release

#1133 Add pch5xxx support
  chipsec/cfg/8086/pch_5xxlp.xml
Labels: Next Release

#1143 Add pch_5xxh config file
  chipsec/cfg/8086/pch_5xxh.xml
Labels: Next Release

#1110 Add util config util command
  chipsec/utilcmd/config_cmd.py
Labels: Next Release, enhancement

#1130 Add messaging for SPI checks
  chipsec/modules/common/spi_access.py
  chipsec/modules/common/spi_desc.py
Labels: Next Release

#1140 ApolloLake / GeminiLake / CherryTrail / Braswell BFPREG Mask Issue
  chipsec/cfg/8086/apl.xml
  chipsec/cfg/8086/cht.xml
  chipsec/cfg/8086/glk.xml
Labels: Next Release, bug

#1141 Specify detection_value ranges
  chipsec/chipset.py
Labels: Next Release, enhancement

#1123 Add CPUID detection value for CPX cpu
  chipsec/cfg/8086/skx.xml
Labels: Next Release, enhancement

#1129 Add new Comet Lake configs
  chipsec/cfg/8086/pch_4xx.xml
  chipsec/cfg/8086/pch_4xxh.xml
Labels: Next Release

#1138 Check the VID is present in the chipset dictionary
  chipsec/chipset.py
Labels: Next Release, enhancement
