Repository chipsec/chipsec, pull requests merged in 2021-07, with the labels that each got.

#1223 Cleanup SKX config
  chipsec/cfg/8086/skx.xml
Labels: Next Release

#1224 Update to support Win11 WDK 10.0.22000 version
  drivers/win7/chipsec_hlpr.inf
  drivers/win7/chipsec_hlpr.sln
  drivers/win7/chipsec_hlpr.vcxproj
Labels: Next Release, enhancement

#1226 Add PCH-Y Premium sku to pch_1xx config
  chipsec/cfg/8086/pch_1xx.xml
Labels: Next Release

#1229 Add ICX platform support
  chipsec/cfg/8086/icx.xml
Labels: Next Release, enhancement

#1199 Modify cs.Cfg.BUS creation
  chipsec/chipset.py
Labels: enhancement, next minor version, validation required

#1200 Change cs functions to use bus not bus_index
  chipsec/chipset.py
Labels: enhancement, next minor version, validation required

#1220 Fixup cs print_register(_all) multibus support
  chipsec/chipset.py
Labels: enhancement, next minor version

#1228 Add log_error() routine
  chipsec/logger.py
Labels: Next Release, enhancement

#1232 Fix hw access errors when looking for efi tables in memory
  chipsec/hal/uefi.py
Labels: Next Release, bug
