Repository chipsec/chipsec, pull requests merged in 2022-08, with the labels that each got.

#1549 Better docstring formatting in whl.xml
  chipsec/cfg/8086/whl.xml
Labels: next release, documentation

#1550 Clean up some flake8 artifacts in uefi_platform.py
  chipsec/hal/uefi_platform.py
Labels: enhancement, next release

#1551 Clean up py2 class object
  chipsec/hal/hal_base.py
  chipsec/hal/paging.py
  chipsec/hal/pci.py
  chipsec/hal/tpm_eventlog.py
  chipsec/helper/basehelper.py
  chipsec/helper/linux/cpuid.py
  chipsec/helper/linux/legacy_pci.py
  chipsec/module_common.py
  chipsec/modules/tools/smm/smm_ptr.py
  chipsec/modules/tools/vmm/common.py
Labels: enhancement, next release

#1552 Clean up py2 code in primitives.py
  chipsec/fuzzing/primitives.py
Labels: enhancement, next release

#1555 Clean up code in uefi_fv.py
  chipsec/hal/uefi_fv.py
Labels: enhancement, next release

#1556 Clean up deprecated py2 code
  chipsec/hal/spd.py
  chipsec/hal/tpm.py
  chipsec/helper/file/filehelper.py
  chipsec/helper/win/win32helper.py
Labels: enhancement, next release

#1558 Remove tabs to fix skipped code when HAL logging level is not set
  chipsec/hal/uefi.py
Labels: next release

#1559 Add VS2022 support to driver and improve documentation
  docs/sphinx/installation/Install in Windows.rst
  drivers/win7/driver.c
Labels: enhancement, next release

#1533 Update the versions used in Github Actions CI
  .github/workflows/tests.yml
Labels: enhancement, next release

#1567 Add arch checks
  chipsec/chipset.py
  chipsec/defines.py
Labels: enhancement, next release

#1564 Update is_supported() in memconfig.py
  chipsec/modules/common/memconfig.py
Labels: next release

#1553 Update to use GitHub Teams to define codeowners
  .github/CODEOWNERS
Labels: next release

#1562 Update tests.yml to include python 3.6 in validation
  .github/workflows/tests.yml
Labels: enhancement, next release

#1548 Better docstring formatting in smm_dma.py
  chipsec/modules/common/smm_dma.py
Labels: enhancement, next release

#1557 Add 600 series pch config
  chipsec/cfg/8086/pch_6xxP.xml
  chipsec/cfg/8086/pch_6xxS.xml
Labels: next release, configuration

#1568 Update pack formatting and improve readability
  chipsec/helper/linux/linuxhelper.py
Labels: enhancement, next release

#1560 drivers/linux: reinstantiate DMA32 allocations
  drivers/linux/chipsec_km.c
  drivers/linux/include/chipsec.h
Labels: next minor version
