Repository chipsec/chipsec, pull requests merged in 2022-12, with the labels that each got.

#1598 Add TypeHints to oshelper.py
  chipsec/helper/oshelper.py
Labels: enhancement, next release

#1605 Fix writemem call to supply correct arguments
  chipsec/helper/efi/efihelper.py
Labels: bug, next release

#1588 Removed deprecated logger functions
  chipsec/chipset.py
  chipsec/logger.py
  chipsec/modules/tools/secureboot/te.py
Labels: enhancement, next release, next minor version

#1607 Add ability to parse FVs that are in a signed FV
  chipsec/hal/spi_uefi.py
  chipsec/hal/uefi_fv.py
  chipsec/hal/uefi_platform.py
Labels: bug, next release

#1622 Exit CHIPSEC if Python 2 found
  chipsec/helper/oshelper.py
Labels: enhancement, next release, next minor version

#1623 Fix compiler warnings for efi/tiano compress
  chipsec_tools/compression/EfiCompress.c
  chipsec_tools/compression/TianoCompress.c
Labels: bug, next release

#1619 Define PEP572 and for-else while-else support
  docs/sphinx/contribution/code-style-python.rst
Labels: enhancement, next release, documentation

#1620 Remove empty class definition parentheses
  chipsec/hal/acpi.py
  chipsec/hal/acpi_tables.py
  chipsec/hal/uefi_common.py
  chipsec/hal/vmm.py
  chipsec/module.py
  chipsec/testcase.py
Labels: enhancement, next release

#1615 Update debian/* for dpkg-buildpackage
  debian/compat
  debian/control
  debian/rules
Labels: bug, enhancement, next release

#1612 Enable codeql on linux driver code
  .github/workflows/codeql.yml
Labels: enhancement, next release

#1614 Add chipsec_main flag for module_exclude
  chipsec_main.py
  docs/sphinx/usage/Running-Chipsec.rst
Labels: enhancement, next release

#1624 Update install documentation to reflect compression changes
  docs/sphinx/installation/Install in Linux.rst
  linux_requirements.txt
Labels: next release, documentation

#1616 Update logger to use python logging
  chipsec/logger.py
  chipsec_main.py
  chipsec_util.py
Labels: next release
