Repository chipsec/chipsec, pull requests merged in 2022-06, with the labels that each got.

#1489 Add usage documentation to ept_finder.py
  chipsec/modules/tools/vmm/ept_finder.py
Labels: enhancement, next release

#1490 Add usage documentation to msr_fuzz.py
  chipsec/modules/tools/vmm/msr_fuzz.py
Labels: enhancement, next release

#1493 Add usage documentation to venom.py
  chipsec/modules/tools/vmm/venom.py
Labels: enhancement, next release

#1494 Add usage documentation to hypercallfuzz.py
  chipsec/modules/tools/vmm/hypercallfuzz.py
Labels: enhancement, next release

#1492 Add usage documentation to pcie_overlap_fuzz.py
  chipsec/modules/tools/vmm/pcie_overlap_fuzz.py
Labels: enhancement, next release

#1495 Minor usage documentation updates to cpuid_fuzz.py
  chipsec/modules/tools/vmm/cpuid_fuzz.py
Labels: enhancement, next release

#1496 Add usage documentation to xsa188.py
  chipsec/modules/tools/vmm/xen/xsa188.py
Labels: enhancement, next release

#1497 Update usage documentation to vmbusfuzz.py
  chipsec/modules/tools/vmm/hv/vmbusfuzz.py
Labels: enhancement, next release

#1500 Update usage documentation in sinkhole.py
  chipsec/modules/tools/cpu/sinkhole.py
Labels: enhancement, next release

#1501 Update logging in spi_cmd.py
  chipsec/utilcmd/spi_cmd.py
Labels: enhancement, next release

#1505 Fix byte buffer prints in hal and tool modules
  chipsec/hal/physmem.py
  chipsec/modules/tools/uefi/s3script_modify.py
  chipsec/modules/tools/vmm/common.py
Labels: bug, next release

#1504 Update duplicated logger functions in chipsec_main.py and chipsec_util.py
  chipsec_main.py
  chipsec_util.py
Labels: enhancement, next release

#1498 Update usage documentation to xen/hypercallfuzz.py
  chipsec/modules/tools/vmm/xen/hypercallfuzz.py
Labels: enhancement, next release

#1506 Correct sku code casing
  chipsec/cfg/8086/pch_4xx.xml
  chipsec/cfg/8086/pch_4xxh.xml
Labels: next release

#1499 Add warning if fv header checksum is invalid
  chipsec/hal/uefi_fv.py
Labels: enhancement, next release

#1508 Updating to 1.8.6
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release

#1518 Update logger.error() in modules
  chipsec/modules/common/uefi/s3bootscript.py
  chipsec/modules/tools/smm/rogue_mmio_bar.py
Labels: enhancement, next release

#1515 Update logger.error() in hal modules
  chipsec/hal/acpi.py
  chipsec/hal/cpu.py
  chipsec/hal/interrupts.py
  chipsec/hal/iobar.py
  chipsec/hal/iommu.py
  chipsec/hal/paging.py
  chipsec/hal/smbus.py
  chipsec/hal/spi.py
  chipsec/hal/spi_descriptor.py
  chipsec/hal/spi_uefi.py
  chipsec/hal/ucode.py
  chipsec/hal/uefi.py
  chipsec/hal/uefi_common.py
  chipsec/hal/uefi_platform.py
  chipsec/hal/vmm.py
Labels: enhancement, next release

#1513 Update .flake8 file to better align with style guide
  .flake8
Labels: enhancement, next release

#1512 Clean up ia_untrusted.py code
  chipsec/modules/common/cpu/ia_untrusted.py
Labels: enhancement, next release

#1510 Update log_verbose() in bios_ts.py and sgx_check.py
  chipsec/modules/common/bios_ts.py
  chipsec/modules/common/sgx_check.py
Labels: enhancement, next release
