Repository chipsec/chipsec, pull requests merged in 2022-07, with the labels that each got.

#1516 Update logger.error() in helper files
  chipsec/helper/dal/dalhelper.py
  chipsec/helper/file/filehelper.py
  chipsec/helper/linux/linuxhelper.py
  chipsec/helper/oshelper.py
  chipsec/helper/osx/osxhelper.py
  chipsec/helper/win/win32helper.py
Labels: enhancement, next release

#1522 Update warn() in hal files
  chipsec/hal/acpi.py
  chipsec/hal/iobar.py
  chipsec/hal/mmio.py
  chipsec/hal/pci.py
  chipsec/hal/spd.py
  chipsec/hal/spi.py
  chipsec/hal/spi_descriptor.py
  chipsec/hal/spi_uefi.py
  chipsec/hal/tpm_eventlog.py
  chipsec/hal/uefi.py
  chipsec/hal/uefi_common.py
  chipsec/hal/uefi_platform.py
Labels: enhancement, next release

#1520 Don't create LEGACY_PCI objects on every access for native mode
  chipsec/helper/linux/linuxhelper.py
Labels: next release

#1521 Update get_device_bus() debug text in chipset.py
  chipsec/chipset.py
Labels: enhancement, next release

#1525 Move wsmt.py to tools
  chipsec/modules/tools/wsmt.py
Labels: next release

#1526 Remove EOL'd rwehelper
  chipsec/helper/helpers.py
  chipsec/helper/rwe/__init__.py
  chipsec/helper/rwe/rwehelper.py
Labels: next release

#1527 Update logger.warn()
  chipsec/helper/file/filehelper.py
  chipsec/helper/linux/linuxhelper.py
  chipsec/helper/win/win32helper.py
Labels: enhancement, next release

#1528 Update verbose_log in module_common.py
  chipsec/module_common.py
Labels: enhancement, next release

#1530 Fixed pylint issue R1719
  chipsec/hal/cpu.py
Labels: enhancement, next release

#1538 Consolidate Linux installation documentation
  docs/sphinx/installation/Install in Linux.rst
  docs/sphinx/installation/Using-CHIPSEC-with-Kali-Linux.rst
  docs/sphinx/start/Download.rst
Labels: next release, documentation

#1539 Remove sphinx warnings
  chipsec/modules/tools/smm/smm_ptr.py
  docs/sphinx/contribution/code-style-python.rst
Labels: next release, documentation

#1540 Improve skipped messaging
  chipsec/logger.py
  chipsec/module.py
  chipsec/modules/tools/secureboot/te.py
  chipsec/testcase.py
  chipsec_main.py
Labels: next release

#1543 Update dead CSW14 link
  README
Labels: next release

#1544 Fix malloc issue in Linux driver
  drivers/linux/chipsec_km.c
Labels: bug, next release

#1546 Update to 1.8.7
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release
