Repository chipsec/chipsec, pull requests merged in 2022-02, with the labels that each got.

#1356 Add usage documentation to sgx_check.py
  chipsec/modules/common/sgx_check.py
Labels: enhancement, next release

#1358 Add usage documentation to smm_code_chk.py
  chipsec/modules/common/smm_code_chk.py
Labels: enhancement, next release

#1366 Fix version update for index.rst
  docs/sphinx/_scripts/getVersion.py
Labels: next release

#1364 Update to 1.8.1
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release

#1374 Remove import debug code
  chipsec_main.py
Labels: next release

#1375 Fix regex reference
  chipsec_main.py
Labels: bug, next release

#1379 Remove google group mailing list
  README.md
Labels: next release

#1383 Configure GitHub Actions to stay on Windows Server 2019 for now
  .github/workflows/tests.yml
Labels: next release

#1385 Fix TPM 1.2 commands logging
  chipsec/hal/tpm.py
Labels: next release

#1387 Fixed exception if size attribute is missing
  chipsec/utilcmd/config_cmd.py
Labels: next release

#1352 Dev 2.0.0 module updates
  chipsec/modules/common/bios_kbrd_buffer.py
  chipsec/modules/common/bios_smi.py
  chipsec/modules/common/bios_ts.py
  chipsec/modules/common/bios_wp.py
  chipsec/modules/common/cpu/cpu_info.py
  chipsec/modules/common/cpu/ia_untrusted.py
  chipsec/modules/common/cpu/spectre_v2.py
  chipsec/modules/common/debugenabled.py
  chipsec/modules/common/ia32cfg.py
  chipsec/modules/common/me_mfg_mode.py
  chipsec/modules/common/memconfig.py
  chipsec/modules/common/memlock.py
  chipsec/modules/common/remap.py
  chipsec/modules/common/rtclock.py
  chipsec/modules/common/secureboot/variables.py
  chipsec/modules/common/sgx_check.py
  chipsec/modules/common/smm.py
  chipsec/modules/common/smm_code_chk.py
  chipsec/modules/common/smm_dma.py
  chipsec/modules/common/smrr.py
  chipsec/modules/common/spd_wd.py
  chipsec/modules/common/spi_access.py
  chipsec/modules/common/spi_desc.py
  chipsec/modules/common/spi_fdopss.py
  chipsec/modules/common/spi_lock.py
  chipsec/modules/common/uefi/access_uefispec.py
  chipsec/modules/common/uefi/s3bootscript.py
  chipsec/modules/common/wsmt.py
  chipsec/modules/tools/cpu/sinkhole.py
  chipsec/modules/tools/secureboot/te.py
  chipsec/modules/tools/smm/rogue_mmio_bar.py
  chipsec/modules/tools/smm/smm_ptr.py
  chipsec/modules/tools/uefi/reputation.py
  chipsec/modules/tools/uefi/s3script_modify.py
  chipsec/modules/tools/uefi/scan_blocked.py
  chipsec/modules/tools/uefi/scan_image.py
  chipsec/modules/tools/uefi/uefivar_fuzz.py
  chipsec/modules/tools/vmm/common.py
  chipsec/modules/tools/vmm/cpuid_fuzz.py
  chipsec/modules/tools/vmm/ept_finder.py
  chipsec/modules/tools/vmm/hv/define.py
  chipsec/modules/tools/vmm/hv/hypercall.py
  chipsec/modules/tools/vmm/hv/hypercallfuzz.py
  chipsec/modules/tools/vmm/hv/synth_dev.py
  chipsec/modules/tools/vmm/hv/synth_kbd.py
  chipsec/modules/tools/vmm/hv/vmbus.py
  chipsec/modules/tools/vmm/hv/vmbusfuzz.py
  chipsec/modules/tools/vmm/hypercallfuzz.py
  chipsec/modules/tools/vmm/iofuzz.py
  chipsec/modules/tools/vmm/msr_fuzz.py
  chipsec/modules/tools/vmm/pcie_fuzz.py
  chipsec/modules/tools/vmm/pcie_overlap_fuzz.py
  chipsec/modules/tools/vmm/vbox/vbox_crash_apicbase.py
  chipsec/modules/tools/vmm/venom.py
  chipsec/modules/tools/vmm/xen/define.py
  chipsec/modules/tools/vmm/xen/hypercall.py
  chipsec/modules/tools/vmm/xen/hypercallfuzz.py
  chipsec/modules/tools/vmm/xen/xsa188.py
Labels: dev branch

#1353 Dev 2.0 helper updates
  chipsec/helper/__init__.py
  chipsec/helper/basehelper.py
  chipsec/helper/dal/__init__.py
  chipsec/helper/dal/dalhelper.py
  chipsec/helper/efi/__init__.py
  chipsec/helper/efi/efihelper.py
  chipsec/helper/file/__init__.py
  chipsec/helper/file/filehelper.py
  chipsec/helper/linux/__init__.py
  chipsec/helper/linux/linuxhelper.py
  chipsec/helper/linuxnative/__init__.py
  chipsec/helper/linuxnative/cpuid.py
  chipsec/helper/linuxnative/legacy_pci.py
  chipsec/helper/linuxnative/linuxnativehelper.py
  chipsec/helper/oshelper.py
  chipsec/helper/osx/osxhelper.py
  chipsec/helper/rwe/__init__.py
  chipsec/helper/rwe/rwehelper.py
  chipsec/helper/win/__init__.py
  chipsec/helper/win/win32helper.py
Labels: dev branch

#1354 Dev 2.0 updates chipsec root folder
  chipsec/chipset.py
  chipsec/command.py
  chipsec/config.py
  chipsec/defines.py
  chipsec/exceptions.py
  chipsec/file.py
  chipsec/module.py
  chipsec/module_common.py
  chipsec/result_deltas.py
  chipsec/testcase.py
Labels: dev branch

#1376 Clairify uefivar_fuzz.py documentation
  chipsec/modules/tools/uefi/uefivar_fuzz.py
Labels: enhancement, next release

#1386 Multi-Bus updates
  chipsec/chipset.py
Labels: next release

#1381 Add routine for control 0xff checks
  chipsec/chipset.py
Labels: enhancement, next release

#1382 Check control return values in bios_ts.py
  chipsec/modules/common/bios_ts.py
Labels: enhancement, next release

#1392 Better device parsing in multi-bus
  chipsec/chipset.py
Labels: enhancement, next release

#1391 Fix bug in is_all_ones when passing size as string from xml config
  chipsec/chipset.py
Labels: bug, next release
