Repository chipsec/chipsec, pull requests merged in 2022-01, with the labels that each got.

#1335 Remove Ubuntu 20.10 from GitHub Actions CI
  .github/workflows/tests.yml
Labels: next release

#1343 dev-2.0.0 GitHub actions fixup
  .github/workflows/tests.yml
Labels: dev branch

#1340 Add TcoCtlLock support
  chipsec/cfg/8086/pch_495.xml
Labels: enhancement, next release

#1346 Add version to manual html pages
  docs/sphinx/_scripts/getVersion.py
Labels: next release

#1333 Fix malformed EFI Section GUID unpacking crash
  chipsec/hal/spi_uefi.py
Labels: bug

#1345 Add usage documentation to rtclock.py
  chipsec/modules/common/rtclock.py
Labels: enhancement, next release

#1357 Revert "extend chipsec_main search to both py and pyc"
  chipsec_main.py
Labels: bug, next release

#1344 Display correct thread when printing (smm_code_chk)
  chipsec/modules/common/smm_code_chk.py
Labels: enhancement, next release

#1341 Add routines to check for all 1's (0xFs)
  chipsec/chipset.py
  chipsec/defines.py
  chipsec/hal/pci.py
Labels: enhancement, next release
