Repository chipsec/chipsec, pull requests merged in 2022-09, with the labels that each got.

#1579 Update 6xxS platform configuration
  chipsec/cfg/8086/pch_6xxS.xml
Labels: next release, configuration

#1570 Add configuration of Intel 440FX PCI and Memory Controller registers
  chipsec/cfg/8086/pmc_i440fx.xml
Labels: bug, next release

#1571 Add a script which starts a QEMU virtual machine with a UEFI shell
  scripts/qemu_efi.py
Labels: enhancement, next release

#1577 Updated pcidb
  chipsec/hal/pcidb.py
Labels: next release

#1580 Add tatlow server DIDs to 500 series pch config
  chipsec/cfg/8086/pch_5xxh.xml
Labels: next release, configuration

#1583 Add SSML register to 4xx cfg from datasheet
  chipsec/cfg/8086/pch_4xx.xml
Labels: enhancement, next release, configuration

#1584 Update Longname of 6xxS PCH devices
  chipsec/cfg/8086/pch_6xxS.xml
Labels: next release, configuration

#1574 Add fw bleed vuln to scan_blocked tool
  chipsec/hal/uefi_search.py
  chipsec/modules/tools/uefi/blockedlist.json
  chipsec/modules/tools/uefi/scan_blocked.py
Labels: enhancement, next release
