Repository chipsec/chipsec, pull requests merged in 2022-03, with the labels that each got.

#1397 Update to 1.8.2
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release

#1401 Fix PMBASE definition in pch_c620
  chipsec/cfg/8086/pch_c620.xml
Labels: next release

#1402 Update python and manual path in setup.py
  setup.py
Labels: next release

#1403 Add usage documentation to bios_kbrd_buffer.py
  chipsec/modules/common/bios_kbrd_buffer.py
Labels: enhancement, next release

#1406 Update get_vsvars.bat to sync with edk
  chipsec_tools/compression/get_vsvars.bat
Labels: enhancement, next release

#1404 Add TGLH support
  chipsec/cfg/8086/tglh.xml
Labels: enhancement, next release

#1405 Architecture document updates
  docs/sphinx/development/Architecture-Overview.rst
  docs/sphinx/development/Configuration-Files.rst
  docs/sphinx/development/Developing.rst
Labels: next release

#1407 Add follow on steps to uefivar_fuzz.py
  chipsec/modules/tools/uefi/uefivar_fuzz.py
Labels: enhancement, next release

#1408 Add usage documentation to debugenabled.py
  chipsec/modules/common/debugenabled.py
Labels: enhancement, next release

#1410 Cleanup and add docstring to wsmt.py
  chipsec/modules/common/wsmt.py
Labels: enhancement, next release

#1413 Fix list-modify-while-iterate bug in bios_wp.py
  chipsec/modules/common/bios_wp.py
Labels: bug, next release

#1414 Correct minor typo in sgx_check.py
  chipsec/modules/common/sgx_check.py
Labels: next release
