Repository chipsec/chipsec, pull requests merged in 2022-05, with the labels that each got.

#1447 Try isatty() in logger.py
  chipsec/logger.py
Labels: enhancement, next release

#1449 Fix GTTMMADR mask for TGLH
  chipsec/cfg/8086/tglh.xml
Labels: next release

#1450 Code clean up in reputation.py
  chipsec/modules/tools/uefi/reputation.py
Labels: enhancement, next release

#1451 Code clean up in scan_blocked.py
  chipsec/modules/tools/uefi/scan_blocked.py
Labels: enhancement, next release

#1453 Code clean up in decode_cmd.py
  chipsec/utilcmd/decode_cmd.py
Labels: enhancement, next release

#1455 Update is_supported() in bios_wp.py
  chipsec/modules/common/bios_wp.py
Labels: enhancement, next release

#1456 Update is_supported() in ia32cfg.py
  chipsec/modules/common/ia32cfg.py
Labels: enhancement, next release

#1457 Update is_supported() in spectre_v2.py
  chipsec/modules/common/cpu/spectre_v2.py
Labels: enhancement, next release

#1459 Update is_supported() in remap.py
  chipsec/modules/common/remap.py
Labels: enhancement, next release

#1461 Update is_supported() in smrr.py
  chipsec/modules/common/smrr.py
Labels: enhancement, next release

#1458 Add usage documentation to memconfig.py
  chipsec/modules/common/memconfig.py
Labels: enhancement, next release

#1463 Add changes to improve documentation
  docs/sphinx/_images/footer.png
  docs/sphinx/_scripts/getVersion.py
  docs/sphinx/_templates/scover.tmpl
  docs/sphinx/_templates/sstylesheet
  docs/sphinx/conf.py
Labels: next release, documentation

#1464 Update AUTHORS for 1.8.4
  AUTHORS
Labels: next release

#1465 Update is_supported() in spi_access.py
  chipsec/modules/common/spi_access.py
Labels: enhancement, next release

#1466 Update is_supported() in spi_desc.py
  chipsec/modules/common/spi_desc.py
Labels: enhancement, next release

#1467 Update is_supported() in sgx_check.py
  chipsec/modules/common/sgx_check.py
Labels: enhancement, next release

#1469 Fix is_supported in smm_dma
  chipsec/modules/common/smm_dma.py
Labels: bug, next release

#1454 Update get_device_bus() behavior in chipset.py and hal/mmio.py
  chipsec/chipset.py
  chipsec/hal/mmio.py
Labels: enhancement, next release

#1470 Update find_EFI_Table() in uefi.py
  chipsec/hal/uefi.py
Labels: enhancement, next release

#1448 Clean up smm_ptr.py
  chipsec/modules/tools/smm/smm_ptr.py
Labels: enhancement, next release

#1474 Add additional verboseness to spi_access.py
  chipsec/modules/common/spi_access.py
Labels: next release

#1479 Replace liveusb with rufus
  docs/sphinx/installation/Install in Linux.rst
Labels: next release

#1481 Updating to 1.8.5
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release

#1483 Correct list numbering in manual
  docs/sphinx/index.rst
Labels: next release

#1484 Fix formatting issue in documentation
  docs/sphinx/installation/USB with UEFI Shell.rst
Labels: next release
