Repository chipsec/chipsec, pull requests merged in 2022-10, with the labels that each got.

#1586 Add type hints to aligned_column_spacing functions
  chipsec/logger.py
Labels: next release, configuration

#1593 Update the wording around the -i flag
  chipsec_main.py
  docs/sphinx/usage/Running-Chipsec.rst
Labels: enhancement, next release, documentation

#1592 Update mailing list and add Discord server link
  docs/sphinx/start/Contact.rst
Labels: next release, documentation

#1595 Update to 1.9.1
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release
