Repository chipsec/chipsec, pull requests merged in 2023-02, with the labels that each got.

#1661 Fix UEFI ACPI guid
  chipsec/hal/acpi_tables.py
Labels: bug, next release

#1663 Correct writemem call to be 3 args
  chipsec/helper/efi/efihelper.py
  chipsec_tools/edk2/PythonEFI/edk2module.c
Labels: bug, next release

#1664 Add VS 2022 tools ('VS170COMNTOOLS') to the list
  drivers/win7/install.cmd
Labels: enhancement, next release

#1665 Update to 1.10.2
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release

#1674 Move to fstrings in chipset.py
  chipsec/chipset.py
Labels: enhancement, next release

#1673 Move SKIPPED results under NOTAPPLICABLE summary
  chipsec/testcase.py
Labels: enhancement, next release

#1672 Type Hint and fstring updates to defines.py
  chipsec/defines.py
Labels: enhancement, next release

#1671 Type Hint and fstring updates to smbus.py
  chipsec/hal/smbus.py
Labels: enhancement, next release

#1668 Type Hint and fstring updates to cpuid.py
  chipsec/hal/cpuid.py
Labels: enhancement, next release

#1667 Type Hint and fstring updates to cpu.py
  chipsec/hal/cpu.py
Labels: enhancement, next release

#1666 Type Hint and fstring updates to physmem.py
  chipsec/hal/physmem.py
Labels: enhancement, next release

#1662 Update doc-string, add Type Hints & fstrings in lock_check_cmd.py
  chipsec/utilcmd/lock_check_cmd.py
Labels: enhancement, next release

#1675 Update GTTMMADR Base Address size
  chipsec/cfg/8086/rpl.xml
Labels: bug, next release, configuration

#1669 Type Hint and fstring updates to pci.py
  chipsec/hal/pci.py
Labels: enhancement, next release

#1682 Type Hint and fstring updates to virtmem.py
  chipsec/hal/virtmem.py
Labels: enhancement, next release

#1681 Type Hint and fstring updates to ec.py
  chipsec/hal/ec.py
Labels: enhancement, next release

#1679 Type Hint and fstring updates to vmm.py
  chipsec/hal/vmm.py
Labels: enhancement, next release

#1678 Type Hint and fstring updates to iommu.py
  chipsec/hal/iommu.py
Labels: enhancement, next release

#1680 Type Hint and fstring updates to mmio.py
  chipsec/hal/mmio.py
Labels: enhancement, next release

#1677 Type Hint and fstring updates to ucode.py
  chipsec/hal/ucode.py
Labels: enhancement, next release

#1685 Update win install doc to include changes to compression changes
  docs/sphinx/installation/Install in Windows.rst
Labels: next release, documentation

#1684 Add MCHBAR to Raptor Lake configuration
  chipsec/cfg/8086/rpl.xml
Labels: next release, configuration

#1688 Don't display extended_banner if using --skip_config
  chipsec_main.py
  chipsec_util.py
Labels: bug, next release

#1689 Type Hint and fstring updates to uefi_fv.py
  chipsec/hal/uefi_fv.py
Labels: enhancement, next release

#1690 Type Hint and fstring updates to tpm.py
  chipsec/hal/tpm.py
Labels: enhancement, next release

#1691 Type Hint and fstring updates to tpm12_commands.py
  chipsec/hal/tpm12_commands.py
Labels: enhancement, next release

#1693 Type Hint and fstring updates to uefi_search.py
  chipsec/hal/uefi_search.py
Labels: enhancement, next release

#1692 Type Hint and fstring updates to uefi_compression.py
  chipsec/hal/uefi_compression.py
Labels: enhancement, next release

#1694 fstring updates to uefi_platform.py
  chipsec/hal/uefi_platform.py
Labels: enhancement, next release

#1695 fstring updates to uefi_common.py
  chipsec/hal/uefi_common.py
Labels: enhancement, next release

#1702 Move 'limit_field' warning under HAL messaging
  chipsec/hal/mmio.py
Labels: next release

#1696 Type Hint and fstring updates to igd.py
  chipsec/hal/igd.py
Labels: enhancement, next release

#1697 Type Hint updates to locks.py
  chipsec/hal/locks.py
Labels: enhancement, next release

#1698 Type Hint and fstring updates to msr.py
  chipsec/hal/msr.py
Labels: enhancement, next release

#1701 fix windows kernel api version dependent issue
  drivers/win7/driver.c
Labels: enhancement

#1699 Type Hint and fstring updates to smbios.py
  chipsec/hal/smbios.py
Labels: enhancement, next release
