Repository chipsec/chipsec, pull requests merged in 2023-04, with the labels that each got.

#1741 f-string updates for uefi folder in tools
  chipsec/modules/tools/uefi/reputation.py
  chipsec/modules/tools/uefi/s3script_modify.py
  chipsec/modules/tools/uefi/scan_blocked.py
  chipsec/modules/tools/uefi/scan_image.py
  chipsec/modules/tools/uefi/uefivar_fuzz.py
Labels: next release

#1686 Update werkzeug version in log_parser\requirements.txt
  chipsec_tools/log_parser/requirements.txt
Labels: validation required

#1743 Fix error when generating pypi package to include .h files
  .gitignore
  MANIFEST.in
Labels: next release

#1744 Add flush method, typehints, fstrings to common.py
  chipsec/modules/tools/vmm/common.py
Labels: bug, enhancement, next release

#1746 f'string updates to vmm hv folder in tools
  chipsec/modules/tools/vmm/hv/define.py
  chipsec/modules/tools/vmm/hv/hypercall.py
  chipsec/modules/tools/vmm/hv/hypercallfuzz.py
  chipsec/modules/tools/vmm/hv/synth_dev.py
  chipsec/modules/tools/vmm/hv/synth_kbd.py
Labels: next release

#1748 Add types.py for common Type Hints
  chipsec/library/__init__.py
  chipsec/library/types.py
Labels: next release

#1749 Add missing methods to efihelper.py
  chipsec/helper/efi/efihelper.py
Labels: enhancement, next release

#1750 Add missing methods to dalhelper.py
  chipsec/helper/dal/dalhelper.py
Labels: enhancement, next release

#1751 Add missing types to oshelper.py
  chipsec/helper/oshelper.py
Labels: next release

#1753 Type Hint and f-string updates to winhelper.py
  chipsec/helper/win/win32helper.py
Labels: enhancement, next release

#1760 f'string updates to msr_fuzz, pcie_fuzz and pcie_overlap_fuzz
  chipsec/modules/tools/vmm/msr_fuzz.py
  chipsec/modules/tools/vmm/pcie_fuzz.py
  chipsec/modules/tools/vmm/pcie_overlap_fuzz.py
Labels: next release

#1759 f'string updates to cpuid_fuzz, hypercallfuzz and iofuzz
  chipsec/modules/tools/vmm/cpuid_fuzz.py
  chipsec/modules/tools/vmm/hypercallfuzz.py
  chipsec/modules/tools/vmm/iofuzz.py
Labels: next release

#1761 Update/improve sphinx
  docs/create_manual.py
  docs/sphinx/_mock/mock_imports.txt
  docs/sphinx/conf.py
Labels: next release

#1752 Type Hint and f-string updates to linuxhelper.py
  chipsec/helper/linux/linuxhelper.py
Labels: enhancement, next release

#1757 f'string updates to vmm subfolders in tools
  chipsec/modules/tools/vmm/hv/vmbusfuzz.py
  chipsec/modules/tools/vmm/vbox/vbox_crash_apicbase.py
  chipsec/modules/tools/vmm/xen/define.py
  chipsec/modules/tools/vmm/xen/hypercall.py
  chipsec/modules/tools/vmm/xen/hypercallfuzz.py
Labels: next release

#1762 Add to the ignored files patterns
  docs/create_manual.py
Labels: next release

#1764 Remove not needed files from not wanted list
  docs/create_manual.py
Labels: next release

#1767 Add workaround if lzma is not importable.
  chipsec/hal/uefi_compression.py
Labels: bug, next release

#1768 Update to 1.10.5
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release
