Repository chipsec/chipsec, pull requests merged in 2023-05, with the labels that each got.

#1779 Fix issue in shell for updated helper loading method
  chipsec/helper/oshelper.py
Labels: bug, next release

#1778 Add pycryptodome to windows requirements list
  windows_requirements.txt
Labels: next release

#1770 adding 2.80 system table revision to fix 'uefi tables' from not workin…
  chipsec/hal/uefi_common.py
Labels: bug, next release

#1769 Fixing broken 'intelsecurity.com' link with wayback link
  chipsec/modules/tools/smm/rogue_mmio_bar.py
Labels: enhancement, next release, documentation

#1776 Bug fixes for SPI Write. Fixes #1775
  chipsec/hal/spi.py
Labels: bug, next release

#1737 Update USBwithUEFIShell.rst manual page for code port
  docs/sphinx/installation/USBwithUEFIShell.rst
Labels: next minor version

#1738 Update qemu_efi.py for code port
  scripts/qemu_efi.py
Labels: next minor version

#1773 Update flask per vulnerability
  chipsec_tools/log_parser/requirements.txt
Labels: bug, next release

#1786 Fix helpers to return correct value for swsmi util
  chipsec/hal/interrupts.py
  chipsec/helper/efi/efihelper.py
  chipsec/helper/linux/linuxhelper.py
  chipsec/helper/oshelper.py
  chipsec/helper/windows/windowshelper.py
Labels: bug, next release

#1784 Add did="0x9D85" name="LP-U" code="PCH_3xxLP"
  chipsec/cfg/8086/pch_3xxop.xml
Labels: configuration

#1777 Remove filehelper
  chipsec/chipset.py
  chipsec/helper/file/__init__.py
  chipsec/helper/file/filehelper.py
  chipsec/helper/helpers.py
  chipsec/helper/oshelper.py
  chipsec_main.py
Labels: next minor release

#1774 Add Intel TXT register definitions from the SEAM Loader
  chipsec/cfg/8086/txt.xml
Labels: next release, configuration

#1771 Remove deprecated log_skipped()
  chipsec/logger.py
Labels: next minor release

#1766 Add flag and check for efi_var_enhanced_auth_access
  chipsec/hal/uefi_common.py
Labels: next minor release

#1772 CHIPSEC_LOADED_AS_EXE support deprecated
  chipsec/file.py
  chipsec/helper/oshelper.py
  chipsec_main.py
  chipsec_util.py
Labels: next minor release

#1792 Remove osx helper and driver
  chipsec/helper/osx/__init__.py
  docs/sphinx/installation/InstallMacOS.rst
  drivers/osx/README
  drivers/osx/chipsec-test/main.c
  drivers/osx/chipsec.xcodeproj/project.pbxproj
  drivers/osx/chipsec.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  drivers/osx/chipsec.xcodeproj/xcuserdata/tweek.xcuserdatad/xcschemes/chipsec.xcscheme
  drivers/osx/chipsec.xcodeproj/xcuserdata/tweek.xcuserdatad/xcschemes/xcschememanagement.plist
  drivers/osx/chipsec/Info.plist
  drivers/osx/chipsec/chipsec.cpp
  drivers/osx/chipsec/chipsec.h
  drivers/osx/chipsec/chipsec_ioctl.h
  drivers/osx/chipsec/cpu.asm
  drivers/osx/chipsec/cpu.h
  setup.py
Labels: next minor release

#1787 Add typehints and fstrings to acpi_cmd.py
  chipsec/utilcmd/acpi_cmd.py
Labels: next release

#1794 Intel TXT: fix some misspellings
  chipsec/cfg/8086/txt.xml
Labels: next release

#1782 Close file if exception thrown during read
  chipsec/file.py
Labels: bug, next release

#1798 Update ucode upload support in dalhelper.py
  chipsec/helper/dal/dalhelper.py
Labels: next release

#1804 Add .run() commands to chipsec_main.py and chipsec_util.py
  chipsec_main.py
  chipsec_util.py
Labels: enhancement, next release

#1806 Update Running-Chipsec.rst to include .run()
  docs/sphinx/usage/Running-Chipsec.rst
Labels: next release, documentation

#1800 Remove get_cpuid() from chipsec_main
  chipsec/chipset.py
  chipsec_main.py
Labels: next release

#1808 Add typehints and fstrings to config_cmd.py
  chipsec/utilcmd/config_cmd.py
Labels: next release

#1801 Remove old logic which attempts to parse Dell PFS proprietary format
  chipsec/hal/spi_uefi.py
  chipsec/hal/uefi_platform.py
Labels: next release

#1797 Add cpu.py unit tests
  tests/hal/__init__.py
  tests/hal/test_cpu.py
Labels: next release

#1799 Add typehints and fstrings to cmos_cmd.py
  chipsec/utilcmd/cmos_cmd.py
Labels: next release

#1807 Add write_unique_file()
  chipsec/defines.py
  chipsec/file.py
Labels: enhancement, next release

#1802 Clean up oshelper
  chipsec/banner.py
  chipsec/chipset.py
  chipsec/helper/oshelper.py
  chipsec/modules/common/cpu/cpu_info.py
  chipsec/modules/common/sgx_check.py
  chipsec/modules/tools/cpu/sinkhole.py
  chipsec/modules/tools/secureboot/te.py
  chipsec_main.py
  chipsec_util.py
  tests/software/util.py
Labels: next minor release

#1803 Clean up HALs and Helpers
  chipsec/hal/interrupts.py
  chipsec/hal/mmio.py
  chipsec/hal/msr.py
  chipsec/hal/physmem.py
  chipsec/hal/uefi.py
  chipsec/hal/virtmem.py
  chipsec/hal/vmm.py
  chipsec/helper/basehelper.py
  chipsec/helper/dal/dalhelper.py
  chipsec/helper/efi/efihelper.py
  chipsec/helper/helpers.py
  chipsec/helper/linux/linuxhelper.py
  chipsec/helper/linuxnative/linuxnativehelper.py
  chipsec/helper/osx/osxhelper.py
  chipsec/helper/windows/windowshelper.py
  tests/software/cs.py
  tests/software/mock_helper.py
  tests/software/test_acpi.py
  tests/software/test_desc.py
Labels: next minor release

#1816 Fix circular dependency with get_datetime_str()
  chipsec/defines.py
  chipsec/file.py
  chipsec/library/string_library.py
Labels: bug, next release

#1814 Fix spidesc table of Master Read/Write Access to Flash Regions
  chipsec/hal/spi_descriptor.py
Labels: bug, next release

#1811 Make chipsec.init() resilient to platform with unknown VID/DID
  chipsec/chipset.py
Labels: bug, next release

#1818 Fix search_efi_tree() return in spi_uefi.py
  chipsec/hal/spi_uefi.py
Labels: bug, next release

#1822 Update to 1.11.0
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release

#1824 Import UnimplementedAPIError from chipsec.exceptions
  chipsec/hal/spi.py
Labels: next release

#1823 Fix SPI write when data size is not a multiple of 4
  chipsec/hal/spi.py
Labels: bug, next release

#1821 Make EC, SMBus and SPD use bytes instead of list of characters
  chipsec/hal/ec.py
  chipsec/hal/smbus.py
  chipsec/hal/spd.py
  chipsec/utilcmd/ec_cmd.py
  chipsec/utilcmd/smbus_cmd.py
Labels: next release
