Repository chipsec/chipsec, pull requests merged in 2023-10, with the labels that each got.

#1955 fix flake8 whitespace errors on smbios.py
  chipsec/hal/smbios.py
Labels: enhancement, next release

#1956 Add module that generates test IDs for return codes
  chipsec/modules/common/remap.py
  chipsec/modules/tools/cpu/sinkhole.py
  chipsec/modules/tools/generate_test_id.py
  chipsec/modules/tools/secureboot/te.py
  chipsec/modules/tools/smm/rogue_mmio_bar.py
  chipsec/modules/tools/smm/smm_ptr.py
  chipsec/modules/tools/vmm/hv/hypercallfuzz.py
  chipsec/modules/tools/vmm/hv/synth_dev.py
  chipsec/modules/tools/vmm/hv/synth_kbd.py
  chipsec/modules/tools/vmm/hv/vmbusfuzz.py
  chipsec/modules/tools/vmm/iofuzz.py
  chipsec/modules/tools/vmm/msr_fuzz.py
  chipsec/modules/tools/vmm/pcie_fuzz.py
  chipsec/modules/tools/vmm/pcie_overlap_fuzz.py
  chipsec/modules/tools/vmm/vbox/vbox_crash_apicbase.py
  chipsec/modules/tools/vmm/venom.py
  chipsec/modules/tools/vmm/xen/hypercallfuzz.py
  chipsec/modules/tools/vmm/xen/xsa188.py
  chipsec/modules/tools/wsmt.py
Labels: next release

#1959 Fix address of UART_3 in Renoir
  chipsec/cfg/1022/renoir.xml
Labels: bug, next release, configuration

#1962 Fix res being referenced before assignment issue
  chipsec/modules/tools/wsmt.py
Labels: next release

#1961 Fix casting issue in TPM HAL
  chipsec/hal/tpm.py
Labels: bug, next release

#1960 Only add pci_dev if not previously added in core_parser
  chipsec/cfg/parsers/core_parsers.py
Labels: bug, next release

#1958 Fix import and possible unbound errors
  chipsec/helper/windows/windowshelper.py
  tests/helpers/test_windowshelper.py
Labels: bug, next release

#1954 Update remaining SKIPPED results and references
  chipsec/module.py
  chipsec/module_common.py
  chipsec/modules/common/smm.py
  chipsec/modules/common/uefi/access_uefispec.py
  chipsec/modules/tools/secureboot/te.py
  chipsec/testcase.py
  chipsec_main.py
  docs/sphinx/usage/Interpreting-Results.rst
  tests/hardware/test_elitebook_1040_ubuntu.py
  tests/hardware/test_generic.py
  tests/hardware/test_x1_carbon_ubuntu.py
  tests/hardware/test_z420_ubuntu.py
Labels: next release

#1964 Update input name to avoid confusion of msr_cmd.py
  chipsec/utilcmd/msr_cmd.py
Labels: enhancement, next release

#1966 Add return codes support to cpu, secureboot and uefi folders in common
  chipsec/modules/common/cpu/cpu_info.py
  chipsec/modules/common/cpu/ia_untrusted.py
  chipsec/modules/common/cpu/spectre_v2.py
  chipsec/modules/common/secureboot/variables.py
  chipsec/modules/common/uefi/access_uefispec.py
  chipsec/modules/common/uefi/s3bootscript.py
Labels: next release

#1967 Update strip_record to fix bug and update run_chipsec_module
  scripts/strip_record_json_of_pcienumeration.py
  tests/modules/run_chipsec_module.py
Labels: bug, next release

#1969 Add return codes support to bios_kbrd_buffer, bios_smi, bios_ts, bios…
  chipsec/modules/common/bios_kbrd_buffer.py
  chipsec/modules/common/bios_smi.py
  chipsec/modules/common/bios_ts.py
  chipsec/modules/common/bios_wp.py
  chipsec/modules/common/debugenabled.py
Labels: next release

#1970 Add check to debugenabled for ECTRL register definition
  chipsec/modules/common/debugenabled.py
Labels: enhancement, next release

#1971 Add return codes support to ia32cfg, me_mfg_mode, memconfig, memlock,…
  chipsec/modules/common/ia32cfg.py
  chipsec/modules/common/me_mfg_mode.py
  chipsec/modules/common/memconfig.py
  chipsec/modules/common/memlock.py
  chipsec/modules/common/rtclock.py
Labels: next release

#1968 Add tgl tests for all modules
  tests/modules/test_tgl_modules.py
  tests/modules/tgl/common-bios_kbrd_buffer_test.json
  tests/modules/tgl/common-bios_smi_test.json
  tests/modules/tgl/common-bios_ts_test.json
  tests/modules/tgl/common-bios_wp_test.json
  tests/modules/tgl/common-cpu-cpu_info_test.json
  tests/modules/tgl/common-cpu-ia_untrusted_test.json
  tests/modules/tgl/common-cpu-spectre_v2_test.json
  tests/modules/tgl/common-debugenabled_test.json
  tests/modules/tgl/common-ia32cfg_test.json
  tests/modules/tgl/common-me_mfg_mode_test.json
  tests/modules/tgl/common-memconfig_test.json
  tests/modules/tgl/common-memlock_test.json
  tests/modules/tgl/common-remap_test.json
  tests/modules/tgl/common-rtclock_test.json
  tests/modules/tgl/common-secureboot-variables_test.json
  tests/modules/tgl/common-sgx_check_test.json
  tests/modules/tgl/common-smm_code_chk_test.json
  tests/modules/tgl/common-smm_dma_test.json
  tests/modules/tgl/common-smm_test.json
  tests/modules/tgl/common-smrr_test.json
  tests/modules/tgl/common-spd_wd_test.json
  tests/modules/tgl/common-spi_access_test.json
  tests/modules/tgl/common-spi_desc_test.json
  tests/modules/tgl/common-spi_fdopss_test.json
  tests/modules/tgl/common-spi_lock_test.json
  tests/modules/tgl/common-uefi-access_uefispec_test.json
  tests/modules/tgl/common-uefi-s3bootscript_test.json
  tests/modules/tgl/enumeration.json
Labels: enhancement, next release

#1965 Add tpm_cmd and txt_cmd unit testing
  chipsec/utilcmd/tpm_cmd.py
  chipsec/utilcmd/txt_cmd.py
  tests/utilcmd/run_chipsec_util.py
  tests/utilcmd/tpm_cmd/adlenumerate.json
  tests/utilcmd/tpm_cmd/test_tpm_cmd.py
  tests/utilcmd/tpm_cmd/tpm_cmd_startup_1.json
  tests/utilcmd/tpm_cmd/tpm_cmd_state_1.json
  tests/utilcmd/txt_cmd/adlenumerate.json
  tests/utilcmd/txt_cmd/test_txt_cmd.py
  tests/utilcmd/txt_cmd/txt_cmd_dump_1.json
  tests/utilcmd/txt_cmd/txt_cmd_state_1.json
Labels: next release

#1972 Update to 1.12.4
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release

#1975 Fix BaseModule call in vmm modules
  chipsec/modules/tools/vmm/hv/hypercallfuzz.py
  chipsec/modules/tools/vmm/iofuzz.py
  chipsec/modules/tools/vmm/msr_fuzz.py
  chipsec/modules/tools/vmm/pcie_fuzz.py
  chipsec/modules/tools/vmm/pcie_overlap_fuzz.py
  chipsec/modules/tools/vmm/vbox/vbox_crash_apicbase.py
  chipsec/modules/tools/vmm/venom.py
  chipsec/modules/tools/vmm/xen/hypercallfuzz.py
  chipsec/modules/tools/vmm/xen/xsa188.py
Labels: bug, next release

#1974 Update Werkzeug requirement per dependabot
  chipsec_tools/log_parser/requirements.txt
Labels: enhancement, next release

#1973 Add return codes support to sgx_check, smm, smm_code_check, smm_dma, smrr
  chipsec/module_common.py
  chipsec/modules/common/sgx_check.py
  chipsec/modules/common/smm.py
  chipsec/modules/common/smm_code_chk.py
  chipsec/modules/common/smm_dma.py
  chipsec/modules/common/smrr.py
Labels: next release
