Repository chipsec/chipsec, pull requests merged in 2023-07, with the labels that each got.

#1832 Fixup how -i, -n and --skip_config are used
  chipsec/chipset.py
  chipsec_main.py
  chipsec_util.py
Labels: bug, enhancement, next minor release

#1882 Add else clause to try block for better flow control
  chipsec/logger.py
Labels: next release

#1883 Update remap.py for when IBECC is enabled (EHL)
  chipsec/modules/common/remap.py
Labels: bug, next release

#1890 Fix infinite loop condition
  chipsec/hal/uefi_platform.py
Labels: bug

#1889 Fix test_pch_invalid() test failing
  tests/software/mock_helper.py
Labels: next minor release

#1891 Remove invalid escape sequences in Windows path
  chipsec/helper/windows/windowshelper.py
Labels: enhancement, next release

#1887 Cpuinfo unittest
  tests/modules/__init__.py
  tests/modules/test_cpu_info.py
Labels: next minor release

#1893 Clean up helper create/start/stop/delete functions
  chipsec/chipset.py
  chipsec/helper/basehelper.py
  chipsec/helper/dal/dalhelper.py
  chipsec/helper/efi/efihelper.py
  chipsec/helper/linux/linuxhelper.py
  chipsec/helper/linuxnative/linuxnativehelper.py
  chipsec/helper/windows/windowshelper.py
  chipsec_main.py
  chipsec_util.py
  tests/helpers/test_linuxhelper.py
  tests/software/mock_helper.py
Labels: enhancement, next minor release

#1895 Fix 'self._get_driver_handle()' function calls in windowshelper.py
  chipsec/helper/windows/windowshelper.py
Labels: bug, next release

#1894 Add record and replay helpers
  chipsec/helper/record/recordhelper.py
  chipsec/helper/replay/replayhelper.py
  tests/helpers/kblreplaytest.json
  tests/helpers/test_recordhelper.py
  tests/helpers/test_replayhelper.py
Labels: enhancement, next minor release

#1897 Add cfg checking tests (non-unittest)
  .github/workflows/tests.yml
  tests/cfg_checker.py
Labels: enhancement, next release

#1900 Add workaround for config loading bug
  chipsec/cfg/parsers/core_parsers.py
Labels: bug, next release

#1901 Update to 1.12.0
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next minor release

#1902 Fix UEFI shell issue with new config loading
  chipsec/config.py
Labels: bug, next minor release
