Repository chipsec/chipsec, pull requests merged in 2023-01, with the labels that each got.

#1631 Update osx pbxproj to exclude arm64e
  drivers/osx/chipsec.xcodeproj/project.pbxproj
Labels: bug, next release

#1633 Define PEP515 support
  docs/sphinx/contribution/code-style-python.rst
Labels: enhancement, next release

#1639 Address some issues in acpi_tables.py
  chipsec/hal/acpi_tables.py
Labels: enhancement, next release

#1638 Fix premature return at module children updating
  chipsec/hal/spi_uefi.py
Labels: bug, next release

#1641 Move debug, hal and verbose log wrappers out of deprecated list
  chipsec/logger.py
Labels: next release

#1643 Type Hint and fstring updates to cmos.py, io.py, and iobar.py
  chipsec/hal/cmos.py
  chipsec/hal/io.py
  chipsec/hal/iobar.py
Labels: enhancement, next release

#1640 Add Type Hints and move to fstrings in acpi_tables.py
  chipsec/hal/acpi_tables.py
Labels: enhancement, next release

#1648 Fix issue with modifying variables in variables.py
  chipsec/modules/common/secureboot/variables.py
Labels: bug, next release

#1646 Change logger to use formatter
  chipsec/logger.py
Labels: enhancement, next release

#1652 Change level code
  chipsec_util.py
Labels: bug, next release

#1654 Add *.log to .gitignore
  .gitignore
Labels: enhancement, next release

#1655 Remove old docker images that are not active and add some new ones
  .github/workflows/tests.yml
Labels: bug, enhancement, next release

#1650 Fix Type Hints in testcase.py
  chipsec/testcase.py
Labels: enhancement, next release

#1653 Add rpl config
  chipsec/cfg/8086/rpl.xml
Labels: next release, configuration

#1649 Remove bytestostring call in edk2.writemem
  chipsec/helper/efi/efihelper.py
Labels: enhancement, next release

#1656 Update to 1.10.1
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release

#1657 Modify RDSP and BERT
  chipsec/hal/acpi.py
  chipsec/hal/acpi_tables.py
Labels: enhancement, next release

#1658 Clear flake8 issues
  chipsec/hal/uefi_compression.py
Labels: next release

#1659 Fix no-member crash errors at logger, uefi
  chipsec/hal/uefi.py
  chipsec/logger.py
Labels: bug, next release

#1660 Add ref lables to contact.rst and code-style-python.rst
  docs/sphinx/contribution/code-style-python.rst
  docs/sphinx/start/Contact.rst
Labels: next release, documentation
