Repository chipsec/chipsec, pull requests merged in 2023-06, with the labels that each got.

#1828 remove the windows build tool version dependency
  drivers/windows/install.cmd
Labels: next release

#1829 Make OsHelper.get_available_helpers return a sorted list
  chipsec/helper/oshelper.py
  chipsec_main.py
  chipsec_util.py
Labels: enhancement, next release

#1836 Add Python 3.11 to Github Action workflow
  .github/workflows/tests.yml
Labels: enhancement, next release

#1817 Banner.py use cs.cpuid value
  chipsec/banner.py
Labels: next release

#1819 Remove hex_to_text from logger
  chipsec/logger.py
Labels: next release

#1831 Move helper.getcwd() from *helper to oshelper
  chipsec/helper/basehelper.py
  chipsec/helper/dal/dalhelper.py
  chipsec/helper/efi/efihelper.py
  chipsec/helper/linux/linuxhelper.py
  chipsec/helper/linuxnative/linuxnativehelper.py
  chipsec/helper/oshelper.py
  chipsec/helper/windows/windowshelper.py
  chipsec/utilcmd/decode_cmd.py
  chipsec/utilcmd/uefi_cmd.py
Labels: enhancement, next release

#1833 Add basic init to Chipset object if only helper is wanted
  chipsec/chipset.py
Labels: enhancement, next release

#1835 Fix Chipset.set_control call to write_register_field
  chipsec/chipset.py
Labels: bug, next release

#1839 Fix Linux native helper MMIO read/write
  chipsec/helper/linuxnative/linuxnativehelper.py
Labels: bug, next release

#1809 Add -nl switch to disable autologging
  chipsec/logger.py
  chipsec_main.py
Labels: next release

#1845 Add 600 Series PCH Device IDs to config
  chipsec/cfg/8086/pch_6xxP.xml
Labels: next release, configuration

#1853 Add Python 3.12 PEP changes to Code Style document
  docs/sphinx/contribution/code-style-python.rst
Labels: enhancement, next release

#1846 Add typehints and fstrings to cpu_cmd.py
  chipsec/utilcmd/cpu_cmd.py
Labels: enhancement, next release

#1848 Add typehints and fstrings to deltas_cmd.py
  chipsec/utilcmd/deltas_cmd.py
Labels: enhancement, next release

#1849 Add typehints and fstrings to desc_cmd.py
  chipsec/utilcmd/desc_cmd.py
Labels: enhancement, next release

#1850 Intel TXT: add field definitions from project Slim Bootloader
  chipsec/cfg/8086/txt.xml
Labels: next release, configuration

#1854 Update core developers list
  AUTHORS
Labels: enhancement, next release

#1863 Add typehints and fstrings to mmcfg_cmd.py
  chipsec/utilcmd/mmcfg_cmd.py
Labels: enhancement, next release

#1862 Add typehints and fstrings to mmcfg_base_cmd.py
  chipsec/utilcmd/mmcfg_base_cmd.py
Labels: enhancement, next release

#1861 Add typehints and fstrings to mem_cmd.py
  chipsec/utilcmd/mem_cmd.py
Labels: enhancement, next release

#1860 Add typehints and fstrings to iommu_cmd.py
  chipsec/utilcmd/iommu_cmd.py
Labels: enhancement, next release

#1859 Add typehints and fstrings to io_cmd.py
  chipsec/utilcmd/io_cmd.py
Labels: enhancement, next release

#1847 Add typehints and fstrings to decode_cmd.py
  chipsec/utilcmd/decode_cmd.py
Labels: enhancement, next release

#1842 Consistent variable return types in uefi_platform.py
  chipsec/hal/uefi.py
  chipsec/hal/uefi_platform.py
Labels: bug, next release

#1812 Rework legacy PCI helper
  chipsec/helper/linuxnative/legacy_pci.py
  chipsec/helper/linuxnative/linuxnativehelper.py
Labels: next release

#1858 Add typehints and fstrings to interrupts_cmd.py
  chipsec/utilcmd/interrupts_cmd.py
Labels: enhancement, next release

#1866 Change default log level to INFO
  chipsec/logger.py
Labels: next release

#1867 Add -nl option to chipsec_util
  chipsec_util.py
Labels: next release

#1856 Add typehints and fstrings to ec_cmd.py
  chipsec/utilcmd/ec_cmd.py
Labels: enhancement, next release

#1857 Add typehints and fstrings to igd_cmd.py
  chipsec/utilcmd/igd_cmd.py
Labels: enhancement, next release

#1868 Update readme.md links
  README.md
Labels: next release, documentation

#1869 Refactor msgbus_send_read/write_message to use msgbus_send_message
  chipsec/helper/linux/linuxhelper.py
Labels: enhancement, next release

#1870 Add initial set of linuxhelper unit tests
  tests/helpers/test_linuxhelper.py
Labels: enhancement, next release

#1871 Fix issues with empty log file names and logs folder creation
  chipsec/logger.py
Labels: next release

#1838 Implement basehelper.py as an ABC
  chipsec/chipset.py
  chipsec/helper/basehelper.py
  chipsec/helper/linuxnative/linuxnativehelper.py
  tests/software/mock_helper.py
Labels: enhancement, next release

#1876 Update usage help messages and help documentation
  chipsec_main.py
  chipsec_util.py
  docs/sphinx/usage/Running-Chipsec.rst
Labels: next release, documentation

#1875 Fix mocked module scoping issue in unittest
  chipsec/helper/helpers.py
  chipsec/helper/oshelper.py
  tests/helpers/__init__.py
  tests/helpers/test_linuxhelper.py
Labels: enhancement, next release

#1873 Fix read/write_mmio_reg call with wrong number of arguments
  chipsec/hal/mmio.py
Labels: bug, next release

#1877 Add win PCI filter driver
  drivers/windows/driver.c
  drivers/windows/pcifilter/filter.c
  drivers/windows/pcifilter/filter.h
  drivers/windows/pcifilter/filter.rc
  drivers/windows/pcifilter/flt_dbg.c
  drivers/windows/pcifilter/flt_dbg.h
  drivers/windows/pcifilter/pcifilter.inf
  drivers/windows/pcifilter/pcifilter.sln
  drivers/windows/pcifilter/pcifilter.vcxproj
  drivers/windows/pcifilter/pcifilter.vcxproj.filters
  drivers/windows/pcifilter/pcifilter.vcxproj.user
Labels: next release

#1879 Win pci filter driver build integration
  .github/workflows/tests.yml
  drivers/windows/chipsec/MAKEFILE
  drivers/windows/chipsec/SOURCES
  drivers/windows/chipsec/amd64/cpu.asm
  drivers/windows/chipsec/chipsec_hlpr.inf
  drivers/windows/chipsec/chipsec_hlpr.rc
  drivers/windows/chipsec/chipsec_hlpr.sln
  drivers/windows/chipsec/chipsec_hlpr.vcxproj
  drivers/windows/chipsec/driver.c
  drivers/windows/chipsec/driver.h
  drivers/windows/chipsec/i386/cpu.asm
  drivers/windows/chipsec/include/chipsec.h
  drivers/windows/chipsec/include/cpu.h
  drivers/windows/chipsec/install.cmd
  drivers/windows/chipsec/readme
  drivers/windows/chipsec/sign/sign64_sys.bat
  drivers/windows/pcifilter/install.cmd
  drivers/windows/pcifilter/pcifilter.vcxproj
  setup.py
Labels: next release

#1881 Update to 1.11.1
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release
