Repository chipsec/chipsec, pull requests merged in 2023-03, with the labels that each got.

#1704 Type Hint and fstring updates to interrupts.py
  chipsec/hal/interrupts.py
Labels: enhancement, next release

#1703 Type Hint and fstring updates to acpi.py
  chipsec/hal/acpi.py
Labels: enhancement, next release

#1706 Update to 1.10.3
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release

#1708 search both deprecated and new win kernel apis, to void compiling compatible issue
  drivers/win7/driver.c
Labels: next release

#1711 Type Hint and fstring updates to uefi_common.py
  chipsec/hal/uefi_common.py
Labels: next release

#1719 Type Hint and fstring updates to spi_jedec_ids.py
  chipsec/hal/spi_jedec_ids.py
Labels: next release

#1712 Type Hint and fstring updates to uefi_platform.py
  chipsec/hal/uefi_platform.py
Labels: next release

#1713 Type Hint and fstring updates to spi.py
  chipsec/hal/spi.py
Labels: next release

#1715 Type Hint and fstring updates to uefi.py
  chipsec/hal/uefi.py
Labels: next release

#1717 Type Hint and fstring updates to msgbus.py
  chipsec/hal/msgbus.py
Labels: next release

#1718 Type Hint and fstring updates to spi_descriptor.py
  chipsec/hal/spi_descriptor.py
Labels: next release

#1721 Fix log in acpi.py
  chipsec/hal/acpi.py
Labels: bug, next release

#1723 f-string updates to /chipsec/. files
  chipsec/exceptions.py
  chipsec/logger.py
  chipsec/module.py
  chipsec/module_common.py
  chipsec/result_deltas.py
  chipsec/testcase.py
Labels: next release

#1709 Updated PCIID database
  chipsec/hal/pcidb.py
Labels: next release

#1722 Fix find_required_col_widths typehint
  chipsec/logger.py
Labels: bug, next release

#1714 Type Hint and fstring updates to spi_uefi.py
  chipsec/hal/spi_uefi.py
Labels: next release

#1725 Type Hint and f-string updates to efihelper.py
  chipsec/helper/efi/efihelper.py
Labels: next release

#1727 Remove sphinx warnings and spaces in installation file names
  chipsec/utilcmd/lock_check_cmd.py
  docs/sphinx/installation/InstallLinux.rst
  docs/sphinx/installation/InstallMacOS.rst
  docs/sphinx/installation/InstallWinDAL.rst
  docs/sphinx/installation/InstallWindows.rst
  docs/sphinx/installation/USBwithUEFIShell.rst
  docs/sphinx/start/Contact.rst
Labels: next release

#1729 Add Elkhart Lake configuration file
  chipsec/cfg/8086/ehl.xml
Labels: next release, configuration

#1728 Consolidate create_manual scripts into one python script
  docs/create_manual.cmd
  docs/create_manual.py
  docs/create_manual.sh
Labels: next release, validation required

#1731 Change all double slashes in directories to os.join.path
  docs/create_manual.py
Labels: next release

#1730 Update to 1.10.4
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release
