Repository chipsec/chipsec, pull requests merged in 2023-08, with the labels that each got.

#1904 Change core_parsers to f'strings and hide register size errors
  chipsec/cfg/parsers/core_parsers.py
Labels: enhancement, next release

#1903 Fix missing 0x in pch_5xxh config
  chipsec/cfg/8086/pch_5xxh.xml
Labels: bug, next release, configuration

#1905 Add typehints to chipsec_tools folder
  chipsec_tools/log_parser/app.py
  chipsec_tools/log_parser/chipsec_parser.py
Labels: enhancement, next release

#1907 Fix helper record test
  tests/helpers/test_recordhelper.py
Labels: next release

#1910 Refix glk detection value (#1735)
  chipsec/cfg/8086/glk.xml
Labels: bug, next release, configuration

#1909 Update sgx_check and vbox_crash_apicbase
  .github/workflows/tests.yml
  chipsec/modules/common/sgx_check.py
  chipsec/modules/tools/vmm/vbox/vbox_crash_apicbase.py
  chipsec_main.py
  tests/modules/sgx_check_1.json
  tests/modules/test_sgx_check.py
Labels: enhancement, next release

#1914 Update lock_check_cmd to poke 'cs.consistency_checking'
  chipsec/chipset.py
  chipsec/utilcmd/lock_check_cmd.py
Labels: bug, next release

#1915 Update cfg_checker test to skip folders
  tests/cfg_checker.py
Labels: next release, configuration

#1918 Update assertRegexpMatch to assertRegex and base Helper to NoneHelper
  chipsec/helper/oshelper.py
  tests/software/util.py
Labels: enhancement, next release

#1917 Print all devices on bus 0 with fun 0 when pch is not detected
  chipsec/banner.py
  chipsec/cfg/parsers/core_parsers.py
  chipsec/chipset.py
  chipsec/config.py
Labels: next release, validation required

#1920 Add pylint pilot test for chipsec/modules folder
  .github/workflows/tests.yml
  .pylintrc
  linux_requirements.txt
  windows_requirements.txt
Labels: next release

#1913 Add PCIe extended capabilities functionality
  chipsec/defines.py
  chipsec/hal/mmio.py
Labels: enhancement, next release

#1923 Port portions of defines.py to architecure.py, bits,py, memory.py, and structs.py
  chipsec/library/architecture.py
  chipsec/library/bits.py
  chipsec/library/memory.py
  chipsec/library/structs.py
Labels: next release

#1922 Move string_library.py to strings.py
  chipsec/file.py
  chipsec/library/strings.py
Labels: next release

#1921 Update docs to reflect recent cfg/helper changes
  docs/sphinx/development/OS-Helpers-and-Drivers.rst
  docs/sphinx/development/Platform-Detection.rst
Labels: next release, documentation

#1924 Update to 1.12.1
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release
