Repository chipsec/chipsec, pull requests merged in 2023-12, with the labels that each got.

#1982 Add typehints and fstrings to common modules
  chipsec/modules/common/bios_kbrd_buffer.py
  chipsec/modules/common/bios_smi.py
  chipsec/modules/common/bios_ts.py
  chipsec/modules/common/bios_wp.py
  chipsec/modules/common/cpu/cpu_info.py
  chipsec/modules/common/cpu/ia_untrusted.py
  chipsec/modules/common/cpu/spectre_v2.py
  chipsec/modules/common/debugenabled.py
  chipsec/modules/common/ia32cfg.py
  chipsec/modules/common/me_mfg_mode.py
  chipsec/modules/common/memconfig.py
  chipsec/modules/common/memlock.py
  chipsec/modules/common/rtclock.py
  chipsec/modules/common/secureboot/variables.py
  chipsec/modules/common/smm.py
  chipsec/modules/common/smm_code_chk.py
  chipsec/modules/common/smm_dma.py
  chipsec/modules/common/smrr.py
  chipsec/modules/common/spd_wd.py
  chipsec/modules/common/spi_access.py
  chipsec/modules/common/spi_desc.py
  chipsec/modules/common/spi_fdopss.py
  chipsec/modules/common/spi_lock.py
  chipsec/modules/common/uefi/access_uefispec.py
  chipsec/modules/common/uefi/s3bootscript.py
Labels: enhancement, next release

#1991 Fix tgl debugenabled unit test replay
  tests/modules/tgl/common-debugenabled_test.json
Labels: bug, next release

#2001 Set the logger.HAL flag to false for unit tests
  tests/modules/run_chipsec_module.py
Labels: enhancement, next release

#2012 Improvements to iommu_cmd list command
  chipsec/utilcmd/iommu_cmd.py
Labels: next release
