Repository chipsec/chipsec, pull requests merged in 2023-11, with the labels that each got.

#1981 Fix return value when not supported
  chipsec/module.py
Labels: bug, next release

#1978 Add _logger.disable() to tests to reduce prints
  tests/modules/run_chipsec_module.py
  tests/modules/test_tgl_modules.py
  tests/utilcmd/run_chipsec_util.py
Labels: enhancement, next release

#1985 Cast module name to lowercase
  chipsec_main.py
Labels: bug, next release

#1977 Make sure DID/VID is printed when platform is unknown
  chipsec/chipset.py
  tests/software/mock_helper.py
  tests/software/test_cs.py
Labels: bug, next release

#1990 Remove mistakenly added log filters from tgl tests
  chipsec/logger.py
  tests/modules/run_chipsec_module.py
  tests/utilcmd/run_chipsec_util.py
Labels: enhancement, next release

#1989 Remove the cpu info cmd from windows ci
  .github/workflows/tests.yml
Labels: bug, next release

#1979 Session 1 extractions
  chipsec/chipset.py
Labels: enhancement

#1976 Add return codes to spd_wd, spi_access, spi_desc, spi_fdopss and spi_…
  chipsec/modules/common/spd_wd.py
  chipsec/modules/common/spi_access.py
  chipsec/modules/common/spi_desc.py
  chipsec/modules/common/spi_fdopss.py
  chipsec/modules/common/spi_lock.py
Labels: next release

#1987 Add a function to handle creation of logs folder
  chipsec/logger.py
Labels: next release
