Repository chipsec/chipsec, pull requests merged in 2023-09, with the labels that each got.

#1926 Fix issues when loading configs
  chipsec/cfg/parsers/core_parsers.py
  chipsec/config.py
Labels: bug, next release

#1930 Import modules traceback and errno when they are needed
  chipsec/chipset.py
  chipsec/modules/tools/vmm/hv/synth_dev.py
  chipsec/modules/tools/vmm/hv/synth_kbd.py
Labels: bug, next release

#1929 Use the right dictionary in handle_ima
  chipsec/cfg/parsers/core_parsers.py
Labels: bug, next release

#1931 Update bus matching check in _process_pci_dev
  chipsec/cfg/parsers/core_parsers.py
  chipsec/chipset.py
  chipsec/config.py
Labels: bug, next release

#1933 Add PEP 632 comments to manual
  docs/sphinx/contribution/code-style-python.rst
Labels: next release

#1934 Update to 1.12.2
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release

#1932 Add get_bits() to library/bits.py
  chipsec/library/bits.py
Labels: next release

#1937 Fix the issue with the bus lists
  chipsec/cfg/parsers/core_parsers.py
  chipsec/chipset.py
  chipsec/exceptions.py
  chipsec/hal/iobar.py
  chipsec/hal/mmio.py
Labels: bug, next release

#1936 Update PCH 6xx* DIDs
  chipsec/cfg/8086/pch_6xxP.xml
  chipsec/cfg/8086/pch_6xxS.xml
Labels: bug, next release, configuration

#1939 Fix uefi_search cpuid.upper call as cpuid is an int
  chipsec/hal/uefi_search.py
Labels: bug, next release

#1935 Update DMAR tables per specification
  chipsec/hal/acpi_tables.py
  chipsec/utilcmd/acpi_cmd.py
Labels: enhancement, next release

#1941 PEP632 URL typo
  docs/sphinx/contribution/code-style-python.rst
Labels: bug, next release, documentation

#1942 Add helper function for return codes integration
  chipsec/module_common.py
Labels: next release

#1950 Fix issue where platform cfgs would not overwrite common
  chipsec/cfg/parsers/core_parsers.py
Labels: bug, next release

#1949 Add return codes support to vmm.venom and wsmt in tools
  chipsec/modules/tools/vmm/venom.py
  chipsec/modules/tools/wsmt.py
Labels: next release

#1948 Add return codes support to iofuzz, msr_fuzz, pcie_fuzz, pcie_overlap…
  chipsec/modules/tools/vmm/iofuzz.py
  chipsec/modules/tools/vmm/msr_fuzz.py
  chipsec/modules/tools/vmm/pcie_fuzz.py
  chipsec/modules/tools/vmm/pcie_overlap_fuzz.py
Labels: next release

#1946 Add return codes support to vbox and xen folders in tools
  chipsec/modules/tools/vmm/vbox/vbox_crash_apicbase.py
  chipsec/modules/tools/vmm/xen/hypercallfuzz.py
  chipsec/modules/tools/vmm/xen/xsa188.py
Labels: next release

#1943 Add check for setuptools >=62.0.0
  setup.py
Labels: next release

#1947 Add return codes support to cpuid_fuzz, ept_finder and hypercallfuzz …
  chipsec/modules/tools/vmm/cpuid_fuzz.py
  chipsec/modules/tools/vmm/ept_finder.py
  chipsec/modules/tools/vmm/hypercallfuzz.py
Labels: next release

#1940 Add return codes support to sinkhole, te, rogue_mmio_bar and smm_ptr
  chipsec/module_common.py
  chipsec/modules/common/remap.py
  chipsec/modules/tools/cpu/sinkhole.py
  chipsec/modules/tools/secureboot/te.py
  chipsec/modules/tools/smm/rogue_mmio_bar.py
  chipsec/modules/tools/smm/smm_ptr.py
Labels: next release

#1951 Add initial windows helper unit tests
  chipsec/helper/windows/windowshelper.py
  tests/helpers/helper_utils.py
  tests/helpers/test_linuxhelper.py
  tests/helpers/test_windowshelper.py
Labels: enhancement, next release

#1953 Update to 1.12.3
  chipsec-manual.pdf
  chipsec/VERSION
  drivers/linux/dkms.conf
Labels: next release
