Repository chipsec/chipsec, pull requests merged in 2024-12, with the labels that each got.

#2365 Update Ubuntu versions in tests.yml
  .github/workflows/tests.yml
Labels: bug, next release, configuration

#2369 Update hal references to use cs.hals
  chipsec/cfg/parsers/registers/io.py
  chipsec/cfg/parsers/registers/iobar.py
  chipsec/cfg/parsers/registers/memory.py
  chipsec/cfg/parsers/registers/mmio.py
  chipsec/cfg/parsers/registers/msgbus.py
  chipsec/hal/common/acpi.py
  chipsec/hal/common/cmos.py
  chipsec/hal/common/ec.py
  chipsec/hal/common/igd.py
  chipsec/hal/common/interrupts.py
  chipsec/hal/common/iobar.py
  chipsec/hal/common/mmio.py
  chipsec/hal/common/msgbus.py
  chipsec/hal/common/paging.py
  chipsec/hal/common/pci.py
  chipsec/hal/common/smbios.py
  chipsec/hal/common/uefi.py
  chipsec/hal/common/vmm.py
  chipsec/hal/intel/spi.py
  chipsec/library/module_ids.json
  chipsec/modules/common/cpu/cpu_info.py
  chipsec/modules/common/rom_armor.py
  chipsec/modules/common/smm_addr.py
  chipsec/modules/common/smrr.py
  chipsec/modules/common/uefi/s3bootscript.py
  chipsec/modules/tools/smm/rogue_mmio_bar.py
  chipsec/modules/tools/smm/smm_ptr.py
  chipsec/modules/tools/uefi/s3script_modify.py
  chipsec/modules/tools/vmm/ept_finder.py
  chipsec/modules/tools/vmm/hv/synth_kbd.py
  chipsec/modules/tools/vmm/hv/vmbus.py
  chipsec/modules/tools/vmm/iofuzz.py
  chipsec/modules/tools/vmm/pcie_fuzz.py
  chipsec/modules/tools/vmm/pcie_overlap_fuzz.py
  chipsec/modules/tools/vmm/venom.py
  chipsec/modules/tools/vmm/xen/hypercall.py
  chipsec/modules/tools/vmm/xen/xsa188.py
  chipsec/utilcmd/igd_cmd.py
  chipsec/utilcmd/io_cmd.py
  chipsec/utilcmd/mem_cmd.py
  chipsec/utilcmd/mmcfg_cmd.py
  chipsec/utilcmd/msgbus_cmd.py
  chipsec/utilcmd/reg_cmd.py
  chipsec/utilcmd/txt_cmd.py
  chipsec/utilcmd/uefi_cmd.py
  tests/hal/test_acpi.py
Labels: dev branch

#2368 Add pch 700 series DIDs into pch 600s config
  chipsec/cfg/8086/pch_6xxS.xml
Labels: next release, configuration

#2371 Increase python's minimum requirement from 3.7 to 3.8
  .github/workflows/tests.yml
  debian/control
  docs/sphinx/contribution/code-style-python.rst
  docs/sphinx/installation/InstallLinux.rst
  docs/sphinx/installation/InstallWinDAL.rst
  docs/sphinx/installation/InstallWindows.rst
Labels: bug, next release, documentation

#2362 SMI enumeration using the standard deviation
  chipsec/modules/tools/smm/smm_ptr.py
Labels: enhancement, next release

#2351 Add util to decode tests' name/id
  chipsec/library/returncode.py
  chipsec/module.py
  chipsec/modules/tools/generate_test_id.py
  chipsec/utilcmd/module_id_cmd.py
  tests/software/test_main.py
Labels: next release

#2363 Check CPU for sample part during sgx_check module
  chipsec/modules/common/sgx_check.py
  chipsec/modules/common/sgx_check_sidekick.py
  chipsec_main.py
  tests/modules/sgx_check_1.json
Labels: next release

#2370 Expands instances of pci registers per bus
  chipsec/cfg/8086/adl.xml
  chipsec/cfg/parsers/ip/pci_device.py
  chipsec/config.py
  chipsec/library/module_ids.json
Labels: dev branch

#2375 Update portio HAL to import halbase and simplify api
  chipsec/cfg/parsers/registers/io.py
  chipsec/cfg/parsers/registers/iobar.py
  chipsec/hal/common/cmos.py
  chipsec/hal/common/ec.py
  chipsec/hal/common/interrupts.py
  chipsec/hal/common/io.py
  chipsec/hal/common/iobar.py
  chipsec/hal/intel/spi.py
  chipsec/library/exceptions.py
  chipsec/modules/tools/vmm/iofuzz.py
  chipsec/modules/tools/vmm/pcie_fuzz.py
  chipsec/modules/tools/vmm/venom.py
  chipsec/utilcmd/io_cmd.py
Labels: dev branch
