Repository chipsec/chipsec, pull requests merged in 2024-03, with the labels that each got.

#2075 Return status in all write port functions
  chipsec/hal/io.py
Labels: next release

#2074 Information and skipped no longer categorized as Failure
  chipsec/module_common.py
Labels: next release

#2090 Add csv log option and fix value returned after running only one test
  chipsec/library/logger.py
  chipsec/module.py
  chipsec/modules/common/cet.py
  chipsec/testcase.py
  chipsec_main.py
Labels: next release

#2103 Update error when running 'uefi var-list' cmd
  chipsec/helper/windows/windowshelper.py
Labels: bug, enhancement, next release

#2106 Fix missing 'f' in f-strings
  chipsec/helper/windows/windowshelper.py
Labels: bug, next release

#2102 Add unit testing for msr_cmd, mmcfg_cmd, mmcfg_base_cmd, desc_cmd and…
  tests/utilcmd/cpu_cmd/cpu_cr_read_1.json
  tests/utilcmd/cpu_cmd/test_cpu_cmd.py
  tests/utilcmd/desc_cmd/gdt_0_1.json
  tests/utilcmd/desc_cmd/idt_0_1.json
  tests/utilcmd/desc_cmd/test_desc_cmd.py
  tests/utilcmd/mmcfg_base_cmd/mmcfg_base_1.json
  tests/utilcmd/mmcfg_base_cmd/test_mmcfg_base_cmd.py
  tests/utilcmd/mmcfg_cmd/mmcfg_base_1.json
  tests/utilcmd/mmcfg_cmd/mmcfg_ec_1.json
  tests/utilcmd/mmcfg_cmd/mmcfg_read_1.json
  tests/utilcmd/mmcfg_cmd/mmcfg_write_1.json
  tests/utilcmd/mmcfg_cmd/test_mmcfg_cmd.py
  tests/utilcmd/msr_cmd/msr_read_1.json
  tests/utilcmd/msr_cmd/msr_read_core_0_1.json
  tests/utilcmd/msr_cmd/msr_write_1.json
  tests/utilcmd/msr_cmd/test_msr_cmd.py
  tests/utilcmd/run_chipsec_util.py
Labels: next release

#2111 Enumerate modules in modules folder using '-lm'
  chipsec/library/file.py
  chipsec/library/module_helper.py
  chipsec_main.py
  tests/software/test_main.py
Labels: enhancement, next release
