Repository chipsec/chipsec, pull requests merged in 2024-09, with the labels that each got.

#2286 Use more generic 'codename' for mSystem in test_generic
  tests/hardware/test_generic.py
Labels: next release

#2288 Update type hints
  chipsec/hal/acpi.py
  chipsec/hal/spi_uefi.py
  chipsec/hal/tpm.py
  chipsec/hal/uefi_common.py
  chipsec/hal/uefi_search.py
  chipsec/helper/linux/linuxhelper.py
  chipsec/helper/linuxnative/cpuid.py
  chipsec/helper/linuxnative/legacy_pci.py
  chipsec/library/banner.py
  chipsec/library/defines.py
  chipsec/library/strings.py
  chipsec_main.py
  chipsec_util.py
  docs/create_manual.py
Labels: next release

#2289 Add gil status reporting
  chipsec/library/banner.py
  chipsec/library/gil.py
Labels: next release

#2290 Reset is_ba_invalid flag when using fixed address
  chipsec/hal/mmio.py
Labels: next release

#2209 Update check for invalid mmio BA value to see if it is all FFs
  chipsec/hal/mmio.py
Labels: enhancement, validation required

#2298 Update distro check in test_generic
  tests/hardware/test_generic.py
Labels: bug, next release

#2300 Fix loading to run some utiles that do not require cfg/driver
  chipsec/cfg/parsers/core_parsers.py
  chipsec/chipset.py
  chipsec/config.py
Labels: bug, next release

#2301 Update chipsec_util to check if a cfg is loaded when it's needed
  chipsec/command.py
  chipsec/config.py
  chipsec/library/defines.py
  chipsec_util.py
Labels: bug, next release

#2291 Update to platform detection
  chipsec/config.py
Labels: bug, enhancement, next release

#2307 Fix replay helper when bytes are stored
  chipsec/helper/replay/replayhelper.py
Labels: bug, next release

#2295 Add exclude module support to options
  chipsec/library/options.py
  chipsec/options/cmd_options.ini
  chipsec_main.py
Labels: next release

#2306 Update HT_UEFI_Rootkit blockedlist entry
  chipsec/modules/tools/uefi/blockedlist.json
Labels: next release

#2305 8086/meteorlake: fix issue #2276
  chipsec/cfg/8086/mtl.xml
Labels: bug, next release, configuration

#2311 Add the ability to change line termination of logger
  chipsec/library/logger.py
Labels: enhancement, next release

#2299 Update functions in UEFI HAL that read EFI variables from ROM
  chipsec/hal/spi.py
  chipsec/hal/uefi.py
  chipsec/helper/windows/windowshelper.py
  chipsec/library/logger.py
  chipsec/utilcmd/uefi_cmd.py
Labels: bug, enhancement, next release

#2312 Fix possible divide by 0 error in read_spi
  chipsec/hal/spi.py
Labels: bug, next release

#2313 Add check to see if reg is defined in txt_cmd
  chipsec/utilcmd/txt_cmd.py
Labels: bug, next release

#2314 Add test data to txt_cmd json for ut
  tests/utilcmd/txt_cmd/txt_cmd_state_1.json
Labels: next release
