Repository chipsec/chipsec, pull requests merged in 2024-01, with the labels that each got.

#2042 Update README.md - Add OpenSSF badge
  README.md
Labels: documentation

#2043 Create SECURITY.md
  SECURITY.md
Labels: documentation

#2044 Fix UEFI Shell issue when importing options.py
  chipsec/options.py
Labels: bug, next release

#2046 Print pci devices when using verbose output
  chipsec/chipset.py
Labels: enhancement, next release

#2035 Update mmcfg command
  chipsec/hal/mmio.py
  chipsec/hal/pci.py
  chipsec/utilcmd/mmcfg_cmd.py
Labels: enhancement, next release

#2048 Add windows PCI filter driver doc
  docs/sphinx/_images/browse_driver.png
  docs/sphinx/_images/check_installed_driver.png
  docs/sphinx/_images/driver_architecture.png
  docs/sphinx/_images/driver_dev_info.png
  docs/sphinx/_images/driver_files.png
  docs/sphinx/_images/driver_files_info.png
  docs/sphinx/_images/install_driver_from_disk.png
  docs/sphinx/_images/installing_driver.png
  docs/sphinx/_images/installing_finished.png
  docs/sphinx/_images/pci_dump_test.png
  docs/sphinx/_images/pci_enum_test.png
  docs/sphinx/_images/pickup_driver.png
  docs/sphinx/_images/restart.png
  docs/sphinx/_images/update_driver.png
  docs/sphinx/installation/InstallWindows.rst
Labels: next release, documentation

#2033 Add CET module
  chipsec/cfg/8086/common.xml
  chipsec/modules/common/cet.py
Labels: enhancement, next release

#2050 Reorder standard Python import statements
  chipsec_util.py
Labels: enhancement

#2051 Update Jinja requirement per dependabot
  chipsec_tools/log_parser/requirements.txt
Labels: bug, next release

#2052 Include options/*.ini when installing using `setup.py install`
  setup.py
Labels: enhancement, next release, configuration

#2054 Resolve mismatch type comparison in uefi_search.py
  chipsec/hal/uefi_search.py
Labels: bug, next release

#2056 Change python to python3 in RunScripts command
  docs/create_manual.py
Labels: next release, documentation
