Repository chipsec/chipsec, pull requests merged in 2024-04, with the labels that each got.

#2114 Remove lines to set test result in is_supported
  chipsec/modules/common/bios_smi.py
  chipsec/modules/common/bios_ts.py
  chipsec/modules/common/bios_wp.py
  chipsec/modules/common/cet.py
  chipsec/modules/common/cpu/cpu_info.py
  chipsec/modules/common/cpu/ia_untrusted.py
  chipsec/modules/common/cpu/spectre_v2.py
  chipsec/modules/common/debugenabled.py
  chipsec/modules/common/ia32cfg.py
  chipsec/modules/common/me_mfg_mode.py
  chipsec/modules/common/memconfig.py
  chipsec/modules/common/memlock.py
  chipsec/modules/common/remap.py
  chipsec/modules/common/rtclock.py
  chipsec/modules/common/secureboot/variables.py
  chipsec/modules/common/sgx_check.py
  chipsec/modules/common/smm.py
  chipsec/modules/common/smm_code_chk.py
  chipsec/modules/common/smm_dma.py
  chipsec/modules/common/smrr.py
  chipsec/modules/common/spd_wd.py
  chipsec/modules/common/spi_access.py
  chipsec/modules/common/spi_desc.py
  chipsec/modules/common/spi_fdopss.py
  chipsec/modules/common/spi_lock.py
  chipsec/modules/common/uefi/access_uefispec.py
  chipsec/modules/common/uefi/s3bootscript.py
Labels: next release

#2129 Add documentation for Sphinx including min and max versions
  docs/sphinx/contribution/sphinx.rst
Labels: next release

#2124 Add default_helper to util_config option section
  chipsec/library/options.py
  chipsec/options/cmd_options.ini
  chipsec_main.py
  chipsec_util.py
Labels: enhancement, next release

#2127 Fix logger references in pci hal
  chipsec/hal/pci.py
Labels: bug, next release

#2123 Update how ACPI Tables are found
  chipsec/hal/acpi.py
  chipsec/helper/basehelper.py
  chipsec/helper/dal/dalhelper.py
  chipsec/helper/efi/efihelper.py
  chipsec/helper/linux/linuxhelper.py
  chipsec/helper/linuxnative/linuxnativehelper.py
  chipsec/helper/nonehelper.py
  chipsec/helper/oshelper.py
  chipsec/helper/record/recordhelper.py
  chipsec/helper/replay/replayhelper.py
  chipsec/helper/windows/windowshelper.py
  tests/helpers/test_linuxhelper.py
  tests/software/mock_helper.py
Labels: bug, enhancement, next release

#2133 Add *.so to .gitignore list
  .gitignore
Labels: enhancement, next release

#2128 Add feature to auto-generate/save return code IDs
  chipsec/library/module_ids.pkl
  chipsec/library/returncode.py
  chipsec/module.py
  chipsec/modules/common/bios_kbrd_buffer.py
  chipsec/modules/common/bios_smi.py
  chipsec/modules/common/bios_ts.py
  chipsec/modules/common/bios_wp.py
  chipsec/modules/common/cet.py
  chipsec/modules/common/cpu/cpu_info.py
  chipsec/modules/common/cpu/ia_untrusted.py
  chipsec/modules/common/cpu/spectre_v2.py
  chipsec/modules/common/debugenabled.py
  chipsec/modules/common/ia32cfg.py
  chipsec/modules/common/me_mfg_mode.py
  chipsec/modules/common/memconfig.py
  chipsec/modules/common/memlock.py
  chipsec/modules/common/remap.py
  chipsec/modules/common/rtclock.py
  chipsec/modules/common/secureboot/variables.py
  chipsec/modules/common/sgx_check.py
  chipsec/modules/common/smm.py
  chipsec/modules/common/smm_code_chk.py
  chipsec/modules/common/smm_dma.py
  chipsec/modules/common/smrr.py
  chipsec/modules/common/spd_wd.py
  chipsec/modules/common/spi_access.py
  chipsec/modules/common/spi_desc.py
  chipsec/modules/common/spi_fdopss.py
  chipsec/modules/common/spi_lock.py
  chipsec/modules/common/uefi/access_uefispec.py
  chipsec/modules/common/uefi/s3bootscript.py
  chipsec/modules/tools/cpu/sinkhole.py
  chipsec/modules/tools/generate_test_id.py
  chipsec/modules/tools/secureboot/te.py
  chipsec/modules/tools/smm/rogue_mmio_bar.py
  chipsec/modules/tools/smm/smm_ptr.py
  chipsec/modules/tools/uefi/reputation.py
  chipsec/modules/tools/uefi/s3script_modify.py
  chipsec/modules/tools/uefi/scan_blocked.py
  chipsec/modules/tools/uefi/uefivar_fuzz.py
  chipsec/modules/tools/vmm/cpuid_fuzz.py
  chipsec/modules/tools/vmm/hv/hypercallfuzz.py
  chipsec/modules/tools/vmm/hv/synth_dev.py
  chipsec/modules/tools/vmm/hv/synth_kbd.py
  chipsec/modules/tools/vmm/hv/vmbusfuzz.py
  chipsec/modules/tools/vmm/hypercallfuzz.py
  chipsec/modules/tools/vmm/iofuzz.py
  chipsec/modules/tools/vmm/msr_fuzz.py
  chipsec/modules/tools/vmm/pcie_fuzz.py
  chipsec/modules/tools/vmm/pcie_overlap_fuzz.py
  chipsec/modules/tools/vmm/vbox/vbox_crash_apicbase.py
  chipsec/modules/tools/vmm/venom.py
  chipsec/modules/tools/vmm/xen/hypercallfuzz.py
  chipsec/modules/tools/vmm/xen/xsa188.py
  chipsec/modules/tools/wsmt.py
  chipsec_main.py
Labels: next release

#2132 Update MMCFG for Avoton to be consistent with other Atoms
  chipsec/cfg/8086/avn.xml
Labels: next release

#2139 Refactor main/util parsing of logger flags
  chipsec/library/logger.py
  chipsec_main.py
  chipsec_util.py
Labels: enhancement, next release
