Repository chipsec/chipsec, pull requests merged in 2024-05, with the labels that each got.

#2162 Change the json module docs url to fully qualified names
  docs/sphinx/_scripts/removeStrRst.py
Labels: next release, documentation

#2164 Add function to compare two ModuleResult's priorities
  chipsec/library/returncode.py
Labels: enhancement, next release

#2173 Add feature so that mmcfg_base reads address for all buses available
  chipsec/hal/mmio.py
  chipsec/utilcmd/mmcfg_base_cmd.py
Labels: next release

#2156 Add UTs for ec_cmd and config_cmd
  chipsec/utilcmd/config_cmd.py
  chipsec/utilcmd/ec_cmd.py
  tests/utilcmd/config_cmd/config_cmd_show_1.json
  tests/utilcmd/config_cmd/test_config_cmd.py
  tests/utilcmd/ec_cmd/ec_cmd_command_1_1.json
  tests/utilcmd/ec_cmd/ec_cmd_dump_1.json
  tests/utilcmd/ec_cmd/ec_cmd_index_1.json
  tests/utilcmd/ec_cmd/ec_cmd_read_2f_1.json
  tests/utilcmd/ec_cmd/ec_cmd_read_2f_4_1.json
  tests/utilcmd/ec_cmd/ec_cmd_write_2f_0_1.json
  tests/utilcmd/ec_cmd/test_ec_cmd.py
Labels: next release

#2141 Add SMI enumeration mode to the smm_ptr module
  chipsec/hal/interrupts.py
  chipsec/helper/linux/linuxhelper.py
  chipsec/modules/tools/smm/smm_ptr.py
  drivers/linux/amd64/cpu.asm
  drivers/linux/chipsec_km.c
  drivers/linux/include/chipsec.h
Labels: next release

#2169 Add feature to automatically generate url for return codes
  chipsec/library/module_ids.json
  chipsec/library/module_ids.pkl
  chipsec/library/url.py
  chipsec/library/url_format.json
  chipsec/module.py
  chipsec/modules/common/bios_kbrd_buffer.py
  chipsec/modules/common/bios_smi.py
  chipsec/modules/common/bios_ts.py
  chipsec/modules/common/bios_wp.py
  chipsec/modules/common/cet.py
  chipsec/modules/common/debugenabled.py
  chipsec/modules/common/me_mfg_mode.py
  chipsec/modules/common/memconfig.py
  chipsec/modules/common/memlock.py
  chipsec/modules/common/remap.py
  chipsec/modules/common/rtclock.py
  chipsec/modules/common/sgx_check.py
  chipsec/modules/common/smm.py
  chipsec/modules/common/smm_code_chk.py
  chipsec/modules/common/smm_dma.py
  chipsec/modules/common/smrr.py
  chipsec/modules/common/spd_wd.py
  chipsec/modules/common/spi_access.py
  chipsec/modules/common/spi_desc.py
  chipsec/modules/common/spi_fdopss.py
  chipsec/modules/common/spi_lock.py
  chipsec/modules/common/uefi/access_uefispec.py
  chipsec/modules/tools/cpu/sinkhole.py
  chipsec/modules/tools/generate_test_id.py
  chipsec/modules/tools/secureboot/te.py
  chipsec/modules/tools/smm/rogue_mmio_bar.py
  chipsec/modules/tools/smm/smm_ptr.py
  chipsec/modules/tools/uefi/reputation.py
  chipsec/modules/tools/uefi/scan_blocked.py
  chipsec/modules/tools/uefi/uefivar_fuzz.py
  chipsec/modules/tools/vmm/cpuid_fuzz.py
  chipsec/modules/tools/vmm/hv/hypercallfuzz.py
  chipsec/modules/tools/vmm/hv/synth_dev.py
  chipsec/modules/tools/vmm/hv/synth_kbd.py
  chipsec/modules/tools/vmm/hv/vmbusfuzz.py
  chipsec/modules/tools/vmm/hypercallfuzz.py
  chipsec/modules/tools/vmm/iofuzz.py
  chipsec/modules/tools/vmm/msr_fuzz.py
  chipsec/modules/tools/vmm/pcie_fuzz.py
  chipsec/modules/tools/vmm/pcie_overlap_fuzz.py
  chipsec/modules/tools/vmm/vbox/vbox_crash_apicbase.py
  chipsec/modules/tools/vmm/venom.py
  chipsec/modules/tools/vmm/xen/hypercallfuzz.py
  chipsec/modules/tools/wsmt.py
Labels: next release

#2174 Add Meteor Lake Support
  chipsec/cfg/8086/mtl.xml
Labels: next release, validation required, configuration
