Repository chipsec/chipsec, pull requests merged in 2024-08, with the labels that each got.

#2247 Replace print() with logger.log()
  chipsec/helper/dal/dalhelper.py
  chipsec/helper/linuxnative/cpuid.py
  chipsec/helper/windows/windowshelper.py
  chipsec/library/logger.py
  chipsec/modules/common/uefi/access_uefispec.py
  chipsec/modules/tools/vmm/common.py
  chipsec/modules/tools/vmm/hv/hypercallfuzz.py
  chipsec/modules/tools/vmm/hv/synth_dev.py
  chipsec/modules/tools/vmm/hv/synth_kbd.py
  chipsec/modules/tools/vmm/hv/vmbus.py
  chipsec/utilcmd/iommu_cmd.py
  chipsec/utilcmd/uefi_cmd.py
Labels: next release

#2250 Fixed fwtype hint to allow NoneType
  chipsec/hal/spi_uefi.py
Labels: next release

#2249 Fixes to scan_image module
  chipsec/modules/tools/uefi/scan_image.py
Labels: next release

#2274 Change MSR_SMM field to all caps
  chipsec/cfg/8086/adl.xml
Labels: next release, configuration

#2275 Replace prints
  chipsec/modules/tools/smm/smm_ptr.py
  chipsec/modules/tools/vmm/common.py
Labels: next release

#2278 Cleanup library
  chipsec/library/banner.py
  chipsec/library/bits.py
  chipsec/library/control.py
  chipsec/library/defines.py
  chipsec/library/device.py
  chipsec/library/exceptions.py
  chipsec/library/file.py
  chipsec/library/lock.py
  chipsec/library/logger.py
  chipsec/library/module_helper.py
  chipsec/library/options.py
  chipsec/library/register.py
  chipsec/library/result_deltas.py
  chipsec/library/returncode.py
Labels: next release

#2277 Helper fstrings
  chipsec/helper/linux/linuxhelper.py
  chipsec/helper/linuxnative/linuxnativehelper.py
  chipsec/helper/oshelper.py
Labels: next release

#2280 Add RM_DIR as global to create_manual.py
  docs/create_manual.py
Labels: bug
