Repository chipsec/chipsec, pull requests merged in 2024-07, with the labels that each got.

#2225 Update req_pch field in mtl configuration
  chipsec/cfg/8086/mtl.xml
Labels: next release, configuration

#2216 Quite the pci enumeration function when --hal flag is set
  chipsec/hal/pci.py
Labels: enhancement, next release

#2233 Update Linux max phys mem write size from 0xFFFF to 0xFFFFFFFF
  chipsec/helper/linux/linuxhelper.py
Labels: bug, next release

#2229 Add error message when UEFI compression modules are missing
  chipsec/hal/uefi_compression.py
Labels: enhancement, next release

#2227 Attempt logger "color" command for ANSI on Windows OS only
  chipsec/library/logger.py
Labels: bug, enhancement, next release

#2232 Update list_IO_BARs function
  chipsec/hal/iobar.py
Labels: bug, next release

#2234 Fix importlib_metadata issue on workflow runner
  .github/workflows/tests.yml
Labels: bug, enhancement, next release

#2235 Add Meteor Lake SPI Support
  chipsec/cfg/8086/mtl.xml
Labels: configuration

#2241 Fix missing size when doing ec dump
  chipsec/utilcmd/ec_cmd.py
Labels: bug, next release

#2237 Add try/except block when copying BARs in rogue_mmio_bar tool
  chipsec/modules/tools/smm/rogue_mmio_bar.py
Labels: bug, next release

#2236 Remove empty () for helper banner
  chipsec/helper/linux/linuxhelper.py
  chipsec/helper/windows/windowshelper.py
  chipsec/library/banner.py
Labels: enhancement, next release
