Repository chipsec/chipsec, pull requests merged in 2024-06, with the labels that each got.

#2180 Fix pcie_fuzz when trying to print devices
  chipsec/hal/pci.py
  chipsec/modules/tools/vmm/pcie_fuzz.py
Labels: bug, next release

#2185 Remove CentOS 8 as it has EOLed
  .github/workflows/tests.yml
Labels: github_actions

#2184 Replace getcwd with get_main_dir
  chipsec/library/url.py
  chipsec/module.py
Labels: bug, next release

#2194 Update GTTMMADR in mtl.xml
  chipsec/cfg/8086/mtl.xml
Labels: next release

#2199 Add more tests for windows helper
  tests/helpers/test_windowshelper.py
Labels: enhancement

#2202 Fix case of SMM_CODE_CHK_EN field
  chipsec/cfg/8086/apl.xml
  chipsec/cfg/8086/bdw.xml
  chipsec/cfg/8086/cfl.xml
  chipsec/cfg/8086/cml.xml
  chipsec/cfg/8086/dnv.xml
  chipsec/cfg/8086/glk.xml
  chipsec/cfg/8086/hsw.xml
  chipsec/cfg/8086/icl.xml
  chipsec/cfg/8086/kbl.xml
  chipsec/cfg/8086/mtl.xml
  chipsec/cfg/8086/rkl.xml
  chipsec/cfg/8086/rpl.xml
  chipsec/cfg/8086/skl.xml
  chipsec/cfg/8086/tglh.xml
  chipsec/cfg/8086/tglu.xml
  chipsec/cfg/8086/whl.xml
  chipsec/modules/common/smm_code_chk.py
Labels: bug, next release, configuration

#2193 Remove Wconio dependency and fix logs folder location
  chipsec/library/logger.py
  windows_requirements.txt
Labels: next release

#2206 Update mmio to check if Base Address is valid
  chipsec/hal/mmio.py
  chipsec/modules/common/bios_ts.py
  chipsec/modules/common/bios_wp.py
  chipsec/modules/common/spi_access.py
  chipsec/modules/common/spi_desc.py
  chipsec/modules/common/spi_fdopss.py
  chipsec/modules/common/spi_lock.py
Labels: bug, next release

#2207 Add get_max_memory_bit_size to physmem hal
  chipsec/hal/physmem.py
Labels: bug, next release
