Repository chipsec/chipsec, pull requests merged in 2024-02, with the labels that each got.

#2057 Fix issues with `chipsec_util.py mmio list` command
  chipsec/chipset.py
  chipsec/hal/mmio.py
Labels: bug, next release

#2059 Fix hal.cpu to not call set_affinity in single threaded env
  chipsec/hal/cpu.py
Labels: bug, next release

#2060 Update attribute assignment conditons for set_EFI_variable
  chipsec/helper/efi/efihelper.py
Labels: bug, next release

#2061 Remove unused functions from logger
  chipsec/logger.py
Labels: next release

#2062 Add return code 'REGISTER_NOT_DEFINED'
  chipsec/module_common.py
Labels: next release

#2064 Move down getReturnCode call to run
  chipsec/modules/common/memconfig.py
Labels: next release

#2065 Return code updates to cet, reputation, s3script_modify and cpuid_fuzz
  chipsec/modules/common/cet.py
  chipsec/modules/tools/uefi/reputation.py
  chipsec/modules/tools/uefi/s3script_modify.py
  chipsec/modules/tools/vmm/cpuid_fuzz.py
Labels: next release

#2066 Return code updates to scan_blocked, uefivar_fuzz and vmm.hypercallfuzz
  chipsec/modules/tools/uefi/scan_blocked.py
  chipsec/modules/tools/uefi/uefivar_fuzz.py
  chipsec/modules/tools/vmm/hypercallfuzz.py
Labels: next release

#2067 Add reg name to error when msr read fails
  chipsec/chipset.py
Labels: enhancement, next release

#2069 Add variables from UEFI spec version 2.10
  chipsec/modules/common/uefi/access_uefispec.py
Labels: next release
