Repository chipsec/chipsec, pull requests merged in 2025-05, with the labels that each got.

#2480 Change root partition size to 1GB
  live_image/mkosi.repart/10-root.conf
Labels: next release

#2491 Sanitize test coverage percentage variable
  .github/workflows/tests.yml
Labels: enhancement, next release

#2488 Add pci write function for hal
  chipsec/hal/common/pci.py
Labels: dev branch

#2496 Updates to DAL helper
  chipsec/helper/dal/dalhelper.py
Labels: next release

#2497 dev/chipsec2 - Add function on objlist 'get_field_value_if_equivalent'
  chipsec/library/register.py
Labels: dev branch

#2498 Add True arguement for SKU data to _config_convert_data() to allow DID ranges
  chipsec/cfg/parsers/core_parsers.py
Labels: bug, dev branch

#2490 Sanitize test coverage percentage variable
  .github/workflows/tests.yml
Labels: enhancement, next release

#2489 Mob/dev2/varstore unit tests
  tests/library/test_varstore.py
Labels: enhancement, next release, dev branch

#2502 Split mmcfg into separate hal
  chipsec/cfg/parsers/registers/mmcfg.py
  chipsec/hal/common/mmio.py
  chipsec/hal/intel/mmcfg.py
  chipsec/library/pci.py
  chipsec/utilcmd/mmcfg_cmd.py
Labels: dev branch

#2475 Revamped HAL compression, added ZLIB and GZIP, improved LZMA
  chipsec/hal/spi_uefi.py
  chipsec/hal/uefi_compression.py
  chipsec/hal/uefi_fv.py
Labels: next release
