Repository chipsec/chipsec, pull requests merged in 2025-01, with the labels that each got.

#2378 Add error message on missing data when using the replayhelper
  chipsec/helper/replay/replayhelper.py
Labels: enhancement, next release

#2389 Add PCH C621A to pch_c260 config file
  chipsec/cfg/8086/pch_c620.xml
Labels: next release, configuration

#2384 Add hal/smbus.py unit tests
  chipsec/hal/smbus.py
  tests/hal/test_smbus.py
Labels: enhancement, next release

#2395 Change install path for chipsec-manual.pdf
  setup.py
Labels: bug, next release
