Repository chipsec/chipsec, pull requests merged in 2025-02, with the labels that each got.

#2405 Change module result to "information" if CPU is a sample part in sgx_check module
  chipsec/modules/common/sgx_check.py
Labels: bug, next release

#2417 Add Windows server 2025 to supported versions in documentation
  docs/sphinx/installation/InstallWindows.rst
Labels: next release, documentation

#2411 dev/chipsec2 - Add logging to hals.py to print stack trace if debugging
  chipsec/hal/hals.py
Labels: dev branch

#2410 Change default logger file name to 'entry'-yearMonDay-Time.log
  chipsec/library/logger.py
  chipsec_main.py
  chipsec_util.py
Labels: enhancement, next release

#2420 dev/chipsec2 fix rebase issue
  chipsec/hal/common/spi_uefi.py
Labels: dev branch

#2418 dev/chipsec2 - Fix up rtclock and smm_dma modules
  chipsec/hal/intel/cpu.py
  chipsec/library/register.py
  chipsec/modules/common/rtclock.py
  chipsec/modules/common/smm_dma.py
  tests/hal/test_cpu.py
Labels: dev branch

#2421 dev/chipsec2 - Update some of the unit tests to run
  chipsec/config.py
  chipsec/library/register.py
  tests/hal/test_cpu.py
  tests/hal/test_smbus.py
  tests/modules/run_chipsec_module.py
  tests/modules/tgl/enumeration.json
  tests/utilcmd/adlenumerate.json
  tests/utilcmd/desc_cmd/gdt_0_1.json
  tests/utilcmd/desc_cmd/idt_0_1.json
  tests/utilcmd/interrupts_cmd/interrupts_cmd_smi_count_1.json
  tests/utilcmd/mem_cmd/__init__.py
  tests/utilcmd/vmem_cmd/__init__.py
Labels: dev branch

#2422 dev/chipsec2 - Add pch_6xxP.xml and child cfgs
  chipsec/cfg/8086/I2C/i2c.xml
  chipsec/cfg/8086/IO/io0.xml
  chipsec/cfg/8086/P2SB/p2sbc1.xml
  chipsec/cfg/8086/PCIE/pcie.xml
  chipsec/cfg/8086/RTC/rtc0.xml
  chipsec/cfg/8086/SATA/abar0.xml
  chipsec/cfg/8086/SATA/sata0.xml
  chipsec/cfg/8086/adl.xml
  chipsec/cfg/8086/pch_6xxp.xml
Labels: dev branch

#2423 Remove MTAG prefix from module tags and add metadata tags
  chipsec/modules/common/bios_kbrd_buffer.py
  chipsec/modules/common/bios_smi.py
  chipsec/modules/common/bios_ts.py
  chipsec/modules/common/bios_wp.py
  chipsec/modules/common/cet.py
  chipsec/modules/common/cpu/cpu_info.py
  chipsec/modules/common/cpu/ia_untrusted.py
  chipsec/modules/common/cpu/spectre_v2.py
  chipsec/modules/common/debugenabled.py
  chipsec/modules/common/ia32cfg.py
  chipsec/modules/common/me_mfg_mode.py
  chipsec/modules/common/memconfig.py
  chipsec/modules/common/memlock.py
  chipsec/modules/common/remap.py
  chipsec/modules/common/rom_armor.py
  chipsec/modules/common/rtclock.py
  chipsec/modules/common/secureboot/variables.py
  chipsec/modules/common/sgx_check.py
  chipsec/modules/common/smm.py
  chipsec/modules/common/smm_addr.py
  chipsec/modules/common/smm_close.py
  chipsec/modules/common/smm_code_chk.py
  chipsec/modules/common/smm_dma.py
  chipsec/modules/common/smm_lock.py
  chipsec/modules/common/smrr.py
  chipsec/modules/common/spd_wd.py
  chipsec/modules/common/spi_access.py
  chipsec/modules/common/spi_desc.py
  chipsec/modules/common/spi_fdopss.py
  chipsec/modules/common/spi_lock.py
  chipsec/modules/common/uefi/access_uefispec.py
  chipsec/modules/tools/cpu/sinkhole.py
  chipsec/modules/tools/secureboot/te.py
  chipsec/modules/tools/smm/rogue_mmio_bar.py
  chipsec/modules/tools/smm/smm_ptr.py
  chipsec/modules/tools/uefi/reputation.py
  chipsec/modules/tools/uefi/s3script_modify.py
  chipsec/modules/tools/uefi/scan_blocked.py
  chipsec/modules/tools/uefi/scan_image.py
  chipsec/modules/tools/uefi/uefivar_fuzz.py
  chipsec/modules/tools/vmm/hv/hypercallfuzz.py
  chipsec/modules/tools/vmm/hv/synth_dev.py
  chipsec/modules/tools/vmm/hv/synth_kbd.py
  chipsec/modules/tools/vmm/hv/vmbusfuzz.py
  chipsec/modules/tools/vmm/vbox/vbox_crash_apicbase.py
  chipsec/modules/tools/vmm/xen/hypercallfuzz.py
  chipsec/modules/tools/vmm/xen/xsa188.py
  chipsec/modules/tools/wsmt.py
Labels: next release

#2428 Add MC1 register check to remap
  chipsec/modules/common/remap.py
Labels: enhancement, next release
